/* Generated by scripts/generate.mjs from schema/generated/projection/ —
 * the Rust DTOs in pointlock-store::projection are the truth source
 * (spine §10.2). DO NOT EDIT BY HAND. */


/**
 * One graph node. `id` is the flow-scoped `stepId` (unique across the
 * whole flow incl. nested regions — compiler-guaranteed, 08 §3.2).
 * 
 * Serde stays lenient because of the flattened kind body (the StepIR
 * pattern); the schema closes the shape via schemars.
 */
export type GraphNode = ({
/**
 * Node id = static `stepId`.
 */
id: string
/**
 * Enclosing step node, when nested inside if/foreach.
 */
parentId?: (string | null)
/**
 * Sub-region of the parent this node belongs to.
 */
region?: (NodeRegion | null)
/**
 * The static runPath anchor (canonical string, no iteration/attempt
 * frames): the join point for run-state overlay and deep links
 * (08 §3.2 — strip `[i]`/`[i:key]` from `RunOverview.steps` keys to
 * land on this anchor).
 */
runPath: string
[k: string]: unknown
} & GraphNode1)
/**
 * Which nested sub-region of the parent a node lives in.
 */
export type NodeRegion = ("then" | "else" | "body")
export type GraphNode1 = ({
/**
 * The act chain channel chips, in `binding.attempts` order
 * (08 §3.4 — one attempt means no fallback, none is invented).
 */
actChain: string[]
/**
 * First bound action name (the primary attempt's).
 */
actionName: string
/**
 * Assertion count badge.
 */
assertionCount: number
kind: "action"
/**
 * `mutating` (solid badge) vs `readonly` (hollow badge).
 */
mutating: boolean
/**
 * Canonical verb, when the step used one (snake_case values).
 */
verb?: (string | null)
[k: string]: unknown
} | {
/**
 * Per-assertion summary rows: assertId + verify chain chips.
 */
assertions: AssertionSummary[]
kind: "assert"
/**
 * `"fresh"` or the referenced `fromStep` step id.
 */
observe: string
[k: string]: unknown
} | {
/**
 * Callee flow id.
 */
calleeFlowId: string
/**
 * Callee content hash (full `sha256:` form; renderers may
 * abbreviate to the 8-hex prefix).
 */
calleeIrHash: string
/**
 * Input key names (values are authoring detail, not graph).
 */
inputKeys: string[]
kind: "call"
[k: string]: unknown
} | {
kind: "human"
/**
 * Interaction mode.
 */
mode: string
/**
 * First line of the prompt.
 */
promptHead: string
/**
 * Response deadline; `on_timeout: unknown` is fixed vocabulary.
 */
timeoutMs: number
[k: string]: unknown
} | {
/**
 * Rendered condition expression summary.
 */
cond: string
/**
 * Whether an else region exists.
 */
hasElse: boolean
kind: "if"
[k: string]: unknown
} | {
/**
 * Iteration variable name.
 */
as: string
/**
 * Rendered items expression summary.
 */
items: string
kind: "foreach"
[k: string]: unknown
} | {
/**
 * Bound variable names.
 */
bindingKeys: string[]
kind: "let"
[k: string]: unknown
})

/**
 * The graph projection of one `FlowIR` (spine §10.1).
 */
export interface FlowGraphView {
/**
 * The closed three-class semantic edges (seq / branch / hook).
 */
edges: GraphEdge[]
/**
 * Flow-level handler badges (hooks with no host step; step-level
 * hooks ride on `hook` edges anchored at their host node).
 */
flowHooks: HookBadge[]
/**
 * The projected flow.
 */
flowId: string
/**
 * The projected flow's content hash (full `sha256:` form).
 */
irHash: string
/**
 * Flat node list; nesting is expressed by `parentId` + `region`.
 */
nodes: GraphNode[]
/**
 * Protocol version (spine §10.3).
 */
projectionVersion: 1
}
/**
 * One semantic edge.
 */
export interface GraphEdge {
/**
 * Source node id.
 */
from: string
/**
 * Handler badge payload, present on `hook` edges.
 */
hook?: (HookBadge | null)
/**
 * Edge class.
 */
kind: ("seq" | "branch" | "hook")
/**
 * Branch label (`"then"` / `"else"`), present on `branch` edges.
 */
label?: (string | null)
/**
 * Target node id; absent on `hook` edges (the badge is the target).
 */
to?: (string | null)
}
/**
 * A handler badge (08 §3.1 hook row): hook + disposition + budget.
 */
export interface HookBadge {
/**
 * Disposition discriminant (`retry`/`continue`/`escalate`/`abort`/`repair`).
 */
disposition: string
/**
 * `onError` class filter, when declared (snake_case values).
 */
errorClasses?: (string[] | null)
/**
 * Hook name (`onFail`/`onUnknown`/`onError`/`onResumeDrift`).
 */
hook: string
/**
 * Trigger budget per instance.
 */
maxTriggers: number
/**
 * Repair target `flowId@sha256:…`, on `repair` dispositions.
 */
repairTarget?: (string | null)
}
/**
 * One assertion summary row on an assert/action node (08 §3.4).
 */
export interface AssertionSummary {
/**
 * The assertion id.
 */
assertId: string
/**
 * Predicate discriminant (`elementState`/`elementText`/`expr`/`visual`).
 */
predicate: string
/**
 * Verify chain chips in `verifyVia` order (vision is always the
 * chain tail and verify-only — principle 7).
 */
verifyVia: string[]
}
