/* Generated by scripts/generate.mjs from schema/generated/projection/ —
 * the Rust DTOs in pointlock-store::projection are the truth source
 * (spine §10.2). DO NOT EDIT BY HAND. */


/**
 * An embedded JSON Schema (Draft 2020-12) document. Deliberately open (exemption class 1): its internal grammar is governed by the JSON Schema meta-schema, not by this schema.
 */
export type JsonSchemaDocument = ({
[k: string]: unknown
} | boolean)
/**
 * One frame of a [`RunPath`] (8 kinds, closed; spine §9), internally tagged
 * with `kind`.
 */
export type PathFrame = ({
/**
 * The flow's id.
 */
flowId: string
/**
 * The flow's content hash.
 */
irHash: string
kind: "flow"
} | {
kind: "step"
/**
 * The step's id.
 */
stepId: string
} | {
/**
 * The callee's flow id.
 */
calleeFlowId: string
/**
 * The callee's content hash.
 */
calleeIrHash: string
kind: "call"
/**
 * The call step's id. Absent exactly when this call frame is a
 * handler-repair launched flow (directly under a `hook` frame,
 * no host call step — spine §9).
 */
stepId?: (StepId | null)
} | {
/**
 * Zero-based iteration index.
 */
index: number
/**
 * Optional stable item key.
 */
key?: (string | null)
kind: "iteration"
} | {
/**
 * The hook that fired.
 */
hook: ("onFail" | "onUnknown" | "onError" | "onResumeDrift")
kind: "hook"
/**
 * One-based trigger count for this hook.
 */
trigger: number
} | {
kind: "attempt"
/**
 * One-based attempt number.
 */
n: number
} | {
kind: "phase"
/**
 * The phase.
 */
phase: ("preflight" | "act" | "observe" | "assert")
} | {
/**
 * The assertion's id.
 */
assertId: string
kind: "assertion"
})
/**
 * Author-written ids use the first segment only ([A-Za-z_][A-Za-z0-9_-]*). ':'-separated segments are reserved for compiler-synthesized ids (e.g. handler-embedded human steps 'host:onFail:escalate'); synthesized ids never appear in ref paths.
 */
export type StepId = string

/**
 * One pending human request (step or supervision — `purpose` is the
 * discriminator, spine A.4).
 */
export interface HumanInboxEntry {
/**
 * Absolute response deadline (ms); absent for supervision gates —
 * they never time out (spine §6.9). After the deadline the runner
 * settles the request to `unknown` (fixed vocabulary).
 */
deadlineAtMs?: (number | null)
/**
 * Confirm labels, when the mode declares them.
 */
decisions?: (string[] | null)
/**
 * The run's flow.
 */
flowId: string
/**
 * Interaction mode (`purpose = step` only).
 */
mode?: (string | null)
/**
 * The provideInput contract, when the mode declares one.
 */
outputSchema?: (JsonSchemaDocument | null)
/**
 * Materialized exhibits (values render directly; evidence refs go
 * through the gallery route — 08 §2.6).
 */
presents: unknown
/**
 * Protocol version (spine §10.3).
 */
projectionVersion: 1
/**
 * The prompt.
 */
prompt: string
/**
 * `step` vs `supervision` (R13).
 */
purpose: string
/**
 * The pairing id a response must carry.
 */
requestId: string
/**
 * When the request was recorded.
 */
requestedAtMs: number
/**
 * Ledger seq of the request.
 */
requestedSeq: number
/**
 * The run awaiting the response.
 */
runId: string
/**
 * Canonical string of the awaiting/gated step's path.
 */
runPath: string
/**
 * The structured path (frames are the authority — spine §9).
 */
runPathFrames: PathFrame[]
}
