/* Generated by scripts/generate.mjs from schema/generated/projection/ —
 * the Rust DTOs in pointlock-store::projection are the truth source
 * (spine §10.2). DO NOT EDIT BY HAND. */


/**
 * One synchronous timeline page (08 §4.4: pagination never moves seen
 * entries; `revision` tells the client when to re-pull).
 */
export interface TimelinePage {
/**
 * The page.
 */
entries: RunTimelineEntry[]
/**
 * Filter applied server-side.
 */
filter: ("all" | "observations" | "actions" | "errors" | "verdicts")
/**
 * 1-based page number.
 */
page: number
/**
 * Effective page size (≤ 50; requests can only shrink it).
 */
pageSize: number
/**
 * Protocol version (spine §10.3).
 */
projectionVersion: 1
/**
 * Snapshot revision (= max ledger seq at query time).
 */
revision: number
/**
 * The projected run.
 */
runId: string
/**
 * Total entries admitted by the filter.
 */
total: number
}
/**
 * One timeline entry (spine §10.1 `RunTimelineEntry`).
 */
export interface RunTimelineEntry {
/**
 * Wall clock, informational only.
 */
atMs: number
/**
 * Bounded typed detail (discriminant = RunLog event type).
 */
detail: ({
/**
 * Supervision policy, explicit `null` when unsupervised (R13).
 */
supervisePolicy?: (string | null)
type: "runStarted"
[k: string]: unknown
} | {
/**
 * The entered step.
 */
stepId: string
type: "stepEntered"
[k: string]: unknown
} | {
/**
 * Failed probes.
 */
fail: number
/**
 * Probe outcome counts as `pass/fail/unknown`.
 */
pass: number
type: "preflightProbed"
/**
 * Unknown probes.
 */
unknown: number
/**
 * The step declared NO probes and this resume re-touched the world
 * without checking it (07 §4.2 rule 1 / I3: 「没有探针的 resume 在
 * 报告中标 `unprobed`，而不是假装校验过」). Stated as a flag, not
 * left to be inferred from three zeroes — the whole point of the
 * rule is that a reader sees it said.
 */
unprobed?: boolean
[k: string]: unknown
} | {
args: BoundedValue
/**
 * The dispatch correlation id.
 */
callId: string
type: "actionIntent"
[k: string]: unknown
} | {
/**
 * The dispatch correlation id.
 */
callId: string
/**
 * Error surface on non-success terminals.
 */
error?: (TimelineErrorView | null)
/**
 * Execution mode when reported (`coordinateFallback` highlighted
 * by renderers).
 */
executionMode?: (string | null)
/**
 * Daemon-side degradation reason, when any.
 */
fallbackReason?: (string | null)
/**
 * Terminal discriminant (`succeeded/failed/cancelled/timedOut`).
 */
outcome: string
type: "actionSettled"
[k: string]: unknown
} | {
/**
 * Capture wall-clock.
 */
capturedAtMs: number
/**
 * Observation id.
 */
observationId: string
/**
 * Screenshot omission reason, when omitted.
 */
screenshotOmission?: (string | null)
type: "observationRecorded"
/**
 * uiSnapshot omission reason, when omitted.
 */
uiSnapshotOmission?: (string | null)
[k: string]: unknown
} | {
/**
 * The assertion.
 */
assertId: string
/**
 * Channel that completed evaluation, when one did.
 */
channel?: (string | null)
/**
 * Bounded reason text.
 */
reason: string
/**
 * Three-valued result.
 */
result: string
type: "assertionEvaluated"
[k: string]: unknown
} | {
/**
 * Degraded-verification marker.
 */
degraded: boolean
/**
 * Bounded `verdict.record` write-back failure — remote archival
 * failed; the local verdict is untouched (04 §5).
 */
remoteArchivalError?: (string | null)
/**
 * Three-valued status.
 */
status: string
/**
 * Bounded verdict summary.
 */
summary: string
/**
 * Superseded verdict id, on re-judgement.
 */
supersedes?: (string | null)
type: "verdictRecorded"
[k: string]: unknown
} | {
/**
 * Exit state (closed vocabulary).
 */
state: ("pending" | "ready" | "probing" | "acting" | "settling" | "observing" | "asserting" | "judged" | "skipped" | "blocked" | "drifted" | "awaitingHuman" | "suspended" | "aborted")
type: "stepExited"
[k: string]: unknown
} | {
/**
 * Callee identity `flowId@sha256:…`.
 */
callee: string
/**
 * The frame was RE-ENTERED under a repaired callee rather than
 * opened (07 §5.2 case (a) down-drill). Absent on every ordinary
 * push and on every pre-incorporation ledger.
 */
rebase?: boolean
type: "callFramePushed"
[k: string]: unknown
} | {
/**
 * Whether the callee returned outputs.
 */
hasOutputs: boolean
type: "callFramePopped"
[k: string]: unknown
} | {
/**
 * Declared disposition head (03 §1.8), when recorded.
 */
disposition?: (string | null)
/**
 * The hook.
 */
hook: string
/**
 * Trigger ordinal for the instance.
 */
trigger: number
type: "handlerTriggered"
[k: string]: unknown
} | {
/**
 * Interaction mode on step requests.
 */
mode?: (string | null)
/**
 * Bounded prompt text.
 */
prompt: string
/**
 * `step` vs `supervision` (R13).
 */
purpose: string
/**
 * Pairing id.
 */
requestId: string
type: "humanRequested"
[k: string]: unknown
} | {
/**
 * Responding actor.
 */
actor: string
/**
 * `step` vs `supervision`.
 */
purpose: string
/**
 * Pairing id.
 */
requestId: string
response: BoundedValue1
type: "humanResponded"
[k: string]: unknown
} | {
/**
 * Suspension reason, explicit `null` when unstated.
 */
reason?: (string | null)
type: "runSuspended"
[k: string]: unknown
} | {
alignment: BoundedValue2
/**
 * Supervision policy of the new segment (explicit `null` when
 * unsupervised — never inherited, R13).
 */
supervisePolicy?: (string | null)
type: "runResumed"
[k: string]: unknown
} | {
/**
 * Degraded marker of the flow verdict.
 */
degraded?: (boolean | null)
/**
 * Bounded `verdict.record` write-back failure of the flow
 * verdict (04 §5 — see `verdictRecorded`).
 */
remoteArchivalError?: (string | null)
/**
 * Flow verdict status; absent = finished unverified/aborted.
 */
status?: (string | null)
type: "runFinished"
[k: string]: unknown
} | {
/**
 * The original event discriminant.
 */
eventType: string
type: "overLimit"
[k: string]: unknown
})
/**
 * Evidence references (≤ 32; pure references — 08 §4.3).
 */
evidence: TimelineEvidenceRef[]
/**
 * How many evidence references were dropped by the cap.
 */
evidenceOmitted: number
/**
 * Canonical run-path string of the event.
 */
runPath: string
/**
 * Ledger sequence — the ordering authority (08 §4.1).
 */
seq: number
/**
 * Whether any field of this entry was truncated while bounding.
 */
truncated: boolean
}
/**
 * Bounded argument snapshot digest.
 */
export interface BoundedValue {
/**
 * Whether anything was cut while bounding.
 */
truncated: boolean
/**
 * The digest value (depth- and size-bounded).
 */
value: unknown
}
/**
 * Typed error surface on error-class entries (08 §4.2: ErrorClass +
 * `ErrorInfo{code, message, retryable}`).
 */
export interface TimelineErrorView {
/**
 * Provider error code (open set).
 */
code: string
/**
 * Closed taxonomy class, when the settlement carried one.
 */
errorClass?: (string | null)
/**
 * Provider error message (bounded).
 */
message: string
/**
 * Whether the provider marked the error retryable.
 */
retryable: boolean
}
/**
 * Bounded response digest.
 */
export interface BoundedValue1 {
/**
 * Whether anything was cut while bounding.
 */
truncated: boolean
/**
 * The digest value (depth- and size-bounded).
 */
value: unknown
}
/**
 * Per-class alignment counts, in class order.
 */
export interface BoundedValue2 {
/**
 * Whether anything was cut while bounding.
 */
truncated: boolean
/**
 * The digest value (depth- and size-bounded).
 */
value: unknown
}
/**
 * One evidence reference on a timeline entry — reference ONLY, never
 * bytes (08 §4.3); dereference goes through the evidence route.
 */
export interface TimelineEvidenceRef {
/**
 * Provider-side asset id.
 */
id: string
/**
 * Media type of the referenced bytes.
 */
mediaType: string
/**
 * Content address of the localized bytes (bare lowercase hex).
 */
sha256: string
}
