/* Generated by scripts/generate.mjs from schema/generated/projection/ —
 * the Rust DTOs in pointlock-store::projection are the truth source
 * (spine §10.2). DO NOT EDIT BY HAND. */


/**
 * The run summary (spine §10.1).
 */
export interface RunOverview {
/**
 * Alignment counts of the latest resume, when the run resumed.
 */
alignment?: (AlignmentSummary | null)
/**
 * Whether a human request is pending (inbox red dot — 08 §3.5).
 */
awaitingHuman: boolean
/**
 * Run creation wall clock.
 */
createdAtMs: number
/**
 * The bound device.
 */
deviceId: string
/**
 * Terminal wall clock, once finished.
 */
finishedAtMs?: (number | null)
/**
 * The run's flow.
 */
flowId: string
/**
 * Degraded marker of the flow verdict.
 */
flowVerdictDegraded?: (boolean | null)
/**
 * Flow verdict status; absent = unfinished, finished unverified, or
 * aborted (the ledger's `runFinished.verdict` as-is — no folding).
 */
flowVerdictStatus?: (string | null)
/**
 * The executed IR (full `sha256:` form).
 */
irHash: string
/**
 * The most recent suspension's provider profile (07 §2.2,
 * incorporated 2026-07-18): present only while the run is actually
 * suspended/awaitingHuman — a superseded suspension profile must
 * not read as current on a resumed or finished run. Named for its
 * timing; the step-anchored captures live in the dossier.
 */
lastSuspensionProviderStateSummary?: (ProviderStateSummary | null)
/**
 * The lockfile digest the run bound against (repair guidance: use
 * the SAME lockfile — 08 §2.7; additive, no version bump).
 */
lockfileDigest: string
/**
 * Protocol version (spine §10.3).
 */
projectionVersion: 1
/**
 * Snapshot revision = max ledger seq (08 §5: the invalidation
 * currency; SSE pushes only `{revision}`).
 */
revision: number
/**
 * The run.
 */
runId: string
/**
 * Session lineage (resume generations — 08 §2.4).
 */
sessionLineage: string[]
/**
 * Ledger status (`running`/`suspended`/`awaitingHuman`/`finished`).
 */
status: string
/**
 * The per-step overlay map, keyed by canonical RunPath string
 * (iteration frames included; strip `[i]`/`[i:key]` to join onto
 * `FlowGraphView` node anchors — 08 §3.2 aggregate rule).
 */
steps: {
[k: string]: StepStateSummary
}
/**
 * Supervision policy of the current segment (explicit `null` when
 * unsupervised — recorded per segment, never inherited; R13).
 */
supervisePolicy?: (string | null)
}
/**
 * Per-class alignment counts of the latest resume (08 §2.4 top bar).
 */
export interface AlignmentSummary {
/**
 * Step + downstream invalidated, re-runs.
 */
effectDirty: number
/**
 * Offline re-judgement, no device redispatch.
 */
judgeDirty: number
/**
 * Newly introduced steps.
 */
new: number
/**
 * Steps whose history lost its IR node.
 */
orphaned: number
/**
 * History kept as-is.
 */
reusable: number
}
/**
 * The provider-side session profile captured at a failure or suspension
 * instant (07 §2.2, incorporated 2026-07-18): pure forensic material for
 * the dossier/overview — resume reconcile, the fold's binding provenance
 * and alignment never consume it. Rides `stepExited` (fail/unknown
 * verdict in force at exit) and `runSuspended` as an additive optional
 * payload field; absent on ledgers recorded before incorporation.
 */
export interface ProviderStateSummary {
attestation: AttestationSnapshot
/**
 * The bound device.
 */
deviceId: string
/**
 * The capture-instant cursor (`currentCursor()` RPC). Absent when
 * the call failed — never a stale bind-time value (principle 4).
 */
eventCursor?: (EventCursor | null)
health: SessionHealthSnapshot
/**
 * `lockfile.device.platform`; absent when the assembly layer did
 * not supply it (the SPI attestation does not carry it).
 */
platform?: (string | null)
/**
 * Known session generations, best-effort: the checkpoint-known
 * lineage plus the live session observed at capture.
 */
sessionLineage: string[]
}
/**
 * The attested capability baseline at capture.
 */
export interface AttestationSnapshot {
/**
 * Attestation timestamp, verbatim.
 */
attestedAt: string
/**
 * Digest of the attested lockfile.
 */
lockfileDigest: string
}
/**
 * Event-log cursor of the bound provider session (spine §6.6; advanced
 * ack-after-persist, never across session generations).
 */
export interface EventCursor {
/**
 * Last sequence durably consumed from that session.
 */
lastSequence: number
/**
 * The provider session that issued the recorded events.
 */
sessionId: string
}
/**
 * `ProviderSession::health()` at capture; a failed call records
 * `{ ok: false, degraded: "<errorClass>" }`.
 */
export interface SessionHealthSnapshot {
/**
 * Degradation note (an error class when the health call failed).
 */
degraded?: (string | null)
/**
 * Whether the session answered healthy.
 */
ok: boolean
}
/**
 * The minimal per-step overlay cell (2026-07-17 ruling, additive).
 */
export interface StepStateSummary {
/**
 * Act-chain runtime marks of the LATEST acting pass (08 §3.4,
 * incorporated 2026-07-18): one entry per SETTLED dispatch, keyed
 * by 1-based chain position — chips beyond the highest marked
 * index render untried by absence. Absent entirely on
 * pre-incorporation ledgers and for undispatched steps (the graph
 * never invents runtime state, principle 4).
 */
actChainMarks?: (ActChainMark[] | null)
/**
 * Degraded-verification marker of that verdict.
 */
degraded?: (boolean | null)
/**
 * Last recorded step state (closed vocabulary).
 */
state: ("pending" | "ready" | "probing" | "acting" | "settling" | "observing" | "asserting" | "judged" | "skipped" | "blocked" | "drifted" | "awaitingHuman" | "suspended" | "aborted")
/**
 * Verdict status once judged.
 */
verdictStatus?: (string | null)
}
/**
 * One settled dispatch of the latest acting pass (08 §3.4). `mark` is
 * the closed chip vocabulary minus `untried` (absence = untried):
 * `succeeded` | `crossed`. `executionMode`/`fallbackReason` ride
 * verbatim so the renderer (which holds the IR) can apply the
 * `acceptExecutionModes` whitelist check.
 */
export interface ActChainMark {
/**
 * 1-based `binding.attempts` position.
 */
chainIndex: number
/**
 * Daemon-reported execution mode, when any.
 */
executionMode?: (string | null)
/**
 * Daemon-side degradation reason, when any.
 */
fallbackReason?: (string | null)
/**
 * `succeeded` | `crossed`.
 */
mark: string
}
