/* Generated by scripts/generate.mjs from schema/generated/projection/ —
 * the Rust DTOs in pointlock-store::projection are the truth source
 * (spine §10.2). DO NOT EDIT BY HAND. */


/**
 * Locating/verification channel (full set, spine A.4).
 * 
 * `vision` is verify-only and `coordinate` is act-only; the FlowIR schema
 * encodes those restrictions structurally via [`ActChannel`] and
 * [`VerifyChannel`].
 */
export type Channel = ("dom" | "uiTree" | "vision" | "coordinate")
/**
 * The closed step union (7 kinds, spine A.4), discriminated by `kind` on
 * the wire. See the module docs for why this is `untagged` in serde while
 * remaining a `kind`-tagged union on the wire.
 */
export type StepIR = (ActionStepIR | AssertStepIR | CallStepIR | HumanStepIR1 | IfStepIR | ForeachStepIR | LetStepIR)
/**
 * A single assertion with its explicit verify-chain.
 * 
 * The three baseline `allOf` conditionals are reproduced on the generated
 * schema via `#[schemars(extend)]`:
 * 1. `expr` predicates consume no observation channel (`verifyVia: []`);
 *    all other predicates need at least one channel.
 * 2. `visual` predicates are vision-only (`verifyVia == ["vision"]`).
 * 3. For `elementState`/`elementText`, `visionPrompt` is required iff the
 *    chain contains `vision`, forbidden otherwise (03 §1.4 rule 5; the
 *    compiler never synthesizes vision prompts, principle 6).
 * 
 * "vision only at the chain tail" is order-sensitive and remains a
 * bind-phase check (not expressible in JSON Schema).
 */
export type AssertionIR = ({
[k: string]: unknown
} & {
/**
 * Stable assertion id (unique within the step).
 */
assertId: string
/**
 * Const `"unknown"` (principle 4): a channel that cannot complete
 * evaluation yields unknown for that channel and the chain advances; an
 * exhausted chain yields unknown. A completed negative is final
 * (spine R5).
 */
onMissingInput: "unknown"
/**
 * The predicate to evaluate.
 */
predicate: ({
selector: ElementSelectorIR
/**
 * The expected state.
 */
state: ("present" | "visible" | "enabled" | "absent")
type: "elementState"
} | {
match: TextMatchIR1
selector: ElementSelectorIR1
type: "elementText"
} | {
/**
 * The boolean expression to evaluate.
 */
expr: (LitExpr | RefExpr | FnExpr)
type: "expr"
} | {
/**
 * Author-written vision prompt.
 */
prompt: string
/**
 * Optional region of interest.
 */
region?: (RectIR | null)
type: "visual"
})
/**
 * Explicit, ordered verify-chain — a subsequence of `[dom, uiTree,
 * vision]`. Order carries semantics (degradation order) and participates
 * verbatim in `judgeHash` (02 §12.1 rule 5). Uniqueness is enforced by
 * the schema (`uniqueItems`), not by this type.
 */
verifyVia: VerifyChannel[]
/**
 * Author-written vision prompt, handed verbatim to the VisionVerifier
 * when `vision` is the declared degraded tail of an
 * `elementState`/`elementText` verify-chain (YAML surface key `visual`).
 * Required iff such a chain contains `vision`, forbidden otherwise.
 * Part of the assertion, hence inside the `judgeHash` domain (02 §12.3).
 */
visionPrompt?: (string | null)
})
/**
 * Whitelisted pure-function application.
 */
export type FnExpr = ({
[k: string]: unknown
} & {
/**
 * Ordered argument expressions.
 */
args: Expr[]
/**
 * The pure function to apply.
 */
fn: ("eq" | "ne" | "not" | "and" | "or" | "concat" | "len" | "coalesce" | "jsonPath" | "regexMatch")
})
/**
 * Expression node: exactly one of `lit` / `ref` / `fn` (02 §8.1).
 * 
 * Wire shape is the baseline schema's `oneOf` of three closed single-key
 * objects; the variants are mutually exclusive by their required keys, so
 * serde's untagged representation is deterministic.
 */
export type Expr = (LitExpr | RefExpr | FnExpr)
/**
 * Channel subset legal on the verify-chain. `coordinate` is structurally
 * excluded (a coordinate cannot verify anything).
 */
export type VerifyChannel = ("dom" | "uiTree" | "vision")
/**
 * Actual execution mode reported by the DeviceRail daemon; the whitelist
 * semantics live on [`crate::BoundAttempt::accept_execution_modes`]
 * (spine §6.4 R-degrade).
 */
export type ExecutionMode = ("nativeSemantic" | "webSemantic" | "coordinateFallback")
/**
 * DeviceRail feature id passthrough (e.g. 'device.semanticActions.v1'); future Pointlock-owned features use the 'pointlock.' prefix.
 */
export type FeatureId = string
/**
 * Pointlock-layer closed error taxonomy (spine §5). DeviceRail
 * `ErrorInfo.code` is an open string set mapped onto this enum.
 * 
 * snake_case on the wire, aligned with DeviceRail error-code style.
 */
export type ErrorClass = ("capability_drift" | "bind_arguments_invalid" | "action_failed_retryable" | "action_failed_final" | "action_timed_out" | "action_cancelled" | "target_stale" | "transport_lost" | "session_degraded")
/**
 * An embedded JSON Schema (Draft 2020-12) document. Deliberately open (exemption class 1): its internal grammar is governed by the JSON Schema meta-schema, not by this schema.
 */
export type JsonSchemaDocument = ({
[k: string]: unknown
} | boolean)
/**
 * Canonical verbs — report/metadata only. The runner has no verb switch;
 * execution is driven exclusively by `BoundAttempt.actionName` (spine R7).
 * 
 * snake_case on the wire (spine A.4).
 */
export type CanonicalVerb = ("tap" | "set_value" | "clear" | "wait_for" | "find" | "observe" | "screenshot" | "invoke")
/**
 * Reason a screenshot was legitimately omitted from an observation
 * (DeviceRail `ScreenshotOmissionReason`, spine A.8; omission is data,
 * not an error — it degrades the verify chain toward `unknown`).
 */
export type ScreenshotOmissionReason = ("policy" | "protectedAction")
/**
 * Reason a UI snapshot was legitimately omitted from an observation
 * (DeviceRail `UiSnapshotOmissionReason`, spine A.8).
 */
export type UiSnapshotOmissionReason = ("driverUnsupported" | "policy" | "protectedAction")
/**
 * One frame of a [`RunPath`] (8 kinds, closed; spine §9), internally tagged
 * with `kind`.
 */
export type PathFrame = ({
/**
 * The flow's id.
 */
flowId: string
/**
 * The flow's content hash.
 */
irHash: string
kind: "flow"
} | {
kind: "step"
/**
 * The step's id.
 */
stepId: string
} | {
/**
 * The callee's flow id.
 */
calleeFlowId: string
/**
 * The callee's content hash.
 */
calleeIrHash: string
kind: "call"
/**
 * The call step's id. Absent exactly when this call frame is a
 * handler-repair launched flow (directly under a `hook` frame,
 * no host call step — spine §9).
 */
stepId?: (StepId | null)
} | {
/**
 * Zero-based iteration index.
 */
index: number
/**
 * Optional stable item key.
 */
key?: (string | null)
kind: "iteration"
} | {
/**
 * The hook that fired.
 */
hook: ("onFail" | "onUnknown" | "onError" | "onResumeDrift")
kind: "hook"
/**
 * One-based trigger count for this hook.
 */
trigger: number
} | {
kind: "attempt"
/**
 * One-based attempt number.
 */
n: number
} | {
kind: "phase"
/**
 * The phase.
 */
phase: ("preflight" | "act" | "observe" | "assert")
} | {
/**
 * The assertion's id.
 */
assertId: string
kind: "assertion"
})
/**
 * Author-written ids use the first segment only ([A-Za-z_][A-Za-z0-9_-]*). ':'-separated segments are reserved for compiler-synthesized ids (e.g. handler-embedded human steps 'host:onFail:escalate'); synthesized ids never appear in ref paths.
 */
export type StepId = string
/**
 * Step lifecycle state (spine §6.2/A.4, closed 14-value set).
 * 
 * `awaitingHuman` doubles as the supervision-gate wait state (R13):
 * the exit path is discriminated by the pending request's `purpose`.
 */
export type StepState = ("pending" | "ready" | "probing" | "acting" | "settling" | "observing" | "asserting" | "judged" | "skipped" | "blocked" | "drifted" | "awaitingHuman" | "suspended" | "aborted")

/**
 * The adjudicable dossier (spine §10.1; = `pointlock locate` JSON).
 */
export interface StepDossierView {
/**
 * Assertion outcomes, in evaluation order.
 */
assertionOutcomes: AssertionOutcomeRecord[]
/**
 * Enriched attempts, in intent order.
 */
attempts: AttemptView[]
/**
 * Effect-identity hash at entry.
 */
effectHash: string
/**
 * Localized evidence references (localPath included — 07 §2.3):
 * observation assets plus every judgment's localized manifest,
 * deduped (sha256, asset.id) first-wins, each with its provenance.
 */
evidence: EvidenceItemView[]
/**
 * Typed localization failures across the judgments (item ③): the
 * honest-gap gallery — a cited-but-unlocalizable asset is a gap
 * tile, never a silent omission.
 */
evidenceGaps?: EvidenceGapView[]
/**
 * Enclosing frame environment, when reconstructable.
 */
frame?: (FrameEnvironment | null)
/**
 * Handler triggers anchored at this instance.
 */
handlerTriggers: HandlerTriggerView[]
/**
 * The IR node in full, when the governing FlowIR artifact was
 * supplied (07 §2.3 part 1; the ledger alone cannot resolve IR).
 */
irNode?: (StepIR | null)
/**
 * Judgement-identity hash at entry.
 */
judgeHash: string
/**
 * Recorded observations (omissions shown as-is).
 */
observations: ObservationRecord[]
/**
 * Step output, once exited with one.
 */
output?: unknown
/**
 * Resume-drift probe outcomes (07 §5), in ledger order.
 */
preflight: AssertionOutcomeRecord[]
/**
 * Protocol version (spine §10.3).
 */
projectionVersion: 1
/**
 * The failure-instant provider profile of this instance's exit
 * (07 §2.2/§2.3 part 4): step-anchored — it rides this instance's
 * own `stepExited`, so it surfaces here even when the live-frame
 * environment join fails closed (popped call frames, later
 * siblings — exactly the post-mortem cases the dossier serves).
 */
providerStateSummary?: (ProviderStateSummary | null)
/**
 * Inputs frozen at `ready`.
 */
resolvedInputs: unknown
/**
 * The queried run.
 */
runId: string
/**
 * Canonical string of the instance path.
 */
runPath: string
/**
 * The structured path (frames are the authority — spine §9).
 */
runPathFrames: PathFrame[]
/**
 * YAML source location, when the artifact was supplied.
 */
source?: (SourceLocation | null)
/**
 * Final exit state, or the frontier state while in flight.
 */
state?: (StepState | null)
/**
 * The step id.
 */
stepId: string
/**
 * The current verdict projection (last recorded), when judged.
 */
verdict?: (StepVerdict | null)
/**
 * The full append-only verdict lineage (supersedes chain).
 */
verdictHistory: VerdictRecordView[]
}
/**
 * Outcome of one assertion evaluation along its verify chain (spine §6.6).
 */
export interface AssertionOutcomeRecord {
/**
 * The assertion's id.
 */
assertId: string
/**
 * The channel that completed the evaluation, when one did.
 */
channel?: (Channel | null)
/**
 * Human-readable evaluation reason.
 */
reason: string
/**
 * Three-valued result (a chain that ran dry is `unknown`, never `fail`).
 */
result: ("pass" | "fail" | "unknown")
}
/**
 * One attempt, enriched beyond the checkpoint's discriminant-only
 * `AttemptRecord` by joining the `actionIntent`/`actionSettled` events
 * (07 §2.2: dossier attempts carry the `ErrorInfo` verbatim + timing).
 */
export interface AttemptView {
/**
 * The dispatched attempt's provider-native action name.
 */
actionName?: (string | null)
/**
 * Dispatch argument snapshot (from the WAL intent).
 */
argsSnapshot: unknown
/**
 * The dispatch correlation id (WAL pairing key).
 */
callId: string
/**
 * 1-based `binding.attempts` chain position (item ②, 2026-07-18);
 * absent on pre-incorporation ledgers.
 */
chainIndex?: (number | null)
/**
 * The dispatched attempt's locating channel (wire literal).
 */
channel?: (string | null)
/**
 * Full provider error on non-success terminals (verbatim).
 */
error?: (ErrorInfo | null)
/**
 * Closed taxonomy class, as the runner recorded it.
 */
errorClass?: (string | null)
/**
 * Declared settlement evidence, verbatim from the terminal's
 * `result.evidence` (item ③ — the provenance join key; the
 * LOCALIZED copies live on the dossier's evidence gallery).
 */
evidence?: AssetRef[]
/**
 * Execution mode the daemon reported.
 */
executionMode?: (string | null)
/**
 * Daemon-side degradation reason, when any.
 */
fallbackReason?: (string | null)
/**
 * Provider-reported finish, on success.
 */
finishedAtMs?: (number | null)
/**
 * Ledger seq of the intent.
 */
intentSeq: number
/**
 * Attempt ordinal from the intent path (`#n`), when recorded.
 */
n?: (number | null)
/**
 * Terminal discriminant (`succeeded/failed/cancelled/timedOut`);
 * absent while the attempt is still in the crash window.
 */
outcome?: (string | null)
/**
 * Ledger seq of the terminal, once settled.
 */
settledSeq?: (number | null)
/**
 * Provider-reported start, on success.
 */
startedAtMs?: (number | null)
}
/**
 * Structured, stable-coded error (DeviceRail `ErrorInfo`, spine A.8).
 * `retryable` is advisory metadata for the runner — providers never retry.
 */
export interface ErrorInfo {
/**
 * Stable error code (open string set on the wire; mapped to the closed
 * `ErrorClass` by the provider adapter, spine §5).
 */
code: string
/**
 * Sanitized structured details.
 */
details?: unknown
/**
 * Human-readable message.
 */
message: string
/**
 * Whether the originator considers the failure retryable.
 */
retryable: boolean
}
/**
 * Content-addressed evidence reference (DeviceRail `AssetRef`, spine A.8).
 * Never inline bytes; `sha256` is the bare hex digest when present.
 */
export interface AssetRef {
/**
 * Provider-scoped asset id (e.g. `sha256:<digest>` or an opaque id).
 */
id: string
/**
 * Media type, e.g. `image/png`.
 */
mediaType: string
/**
 * Bare lowercase hex sha256 digest of the content, when known.
 */
sha256?: (string | null)
/**
 * Provider URI, e.g. `devicerail://assets/sha256/<digest>`.
 */
uri: string
}
/**
 * One localized gallery item with its provenance (08 §2.5: the
 * evidence tile says WHICH observation/judgment produced it).
 */
export interface EvidenceItemView {
asset: AssetRef1
/**
 * Path inside the store's content-addressed evidence area.
 */
localPath: string
/**
 * Bare lowercase hex sha256 digest of the localized bytes.
 */
sha256: string
/**
 * Provenance label: `observation:<id>/screenshot`,
 * `observation:<id>/uiSnapshot`, `verdict@seq:<n>` (that judgment's
 * settlement/human evidence), or `exit@seq:<n>` (an unverified
 * exit's manifest).
 */
source: string
}
/**
 * Content-addressed evidence reference (DeviceRail `AssetRef`, spine A.8).
 * Never inline bytes; `sha256` is the bare hex digest when present.
 */
export interface AssetRef1 {
/**
 * Provider-scoped asset id (e.g. `sha256:<digest>` or an opaque id).
 */
id: string
/**
 * Media type, e.g. `image/png`.
 */
mediaType: string
/**
 * Bare lowercase hex sha256 digest of the content, when known.
 */
sha256?: (string | null)
/**
 * Provider URI, e.g. `devicerail://assets/sha256/<digest>`.
 */
uri: string
}
/**
 * One aggregated localization gap of the dossier (item ③): the payload
 * gap plus its verdict-event anchor.
 */
export interface EvidenceGapView {
asset: AssetRef2
/**
 * Why localization failed.
 */
reason: string
/**
 * Ledger seq of the recording `verdictRecorded` event.
 */
seq: number
}
/**
 * Content-addressed evidence reference (DeviceRail `AssetRef`, spine A.8).
 * Never inline bytes; `sha256` is the bare hex digest when present.
 */
export interface AssetRef2 {
/**
 * Provider-scoped asset id (e.g. `sha256:<digest>` or an opaque id).
 */
id: string
/**
 * Media type, e.g. `image/png`.
 */
mediaType: string
/**
 * Bare lowercase hex sha256 digest of the content, when known.
 */
sha256?: (string | null)
/**
 * Provider URI, e.g. `devicerail://assets/sha256/<digest>`.
 */
uri: string
}
/**
 * The enclosing frame environment (07 §2.3 part 4).
 */
export interface FrameEnvironment {
/**
 * Call-by-value inputs snapshot of the enclosing frame.
 */
inputsSnapshot: unknown
/**
 * The failure-instant provider profile of this step's exit
 * (07 §2.2/§2.3 part 4, incorporated 2026-07-18): present only for
 * fail/unknown-verdict exits on post-incorporation ledgers.
 */
providerStateSummary?: (ProviderStateSummary | null)
/**
 * `let` bindings visible in the frame.
 */
vars: {
[k: string]: unknown
}
}
/**
 * The provider-side session profile captured at a failure or suspension
 * instant (07 §2.2, incorporated 2026-07-18): pure forensic material for
 * the dossier/overview — resume reconcile, the fold's binding provenance
 * and alignment never consume it. Rides `stepExited` (fail/unknown
 * verdict in force at exit) and `runSuspended` as an additive optional
 * payload field; absent on ledgers recorded before incorporation.
 */
export interface ProviderStateSummary {
attestation: AttestationSnapshot
/**
 * The bound device.
 */
deviceId: string
/**
 * The capture-instant cursor (`currentCursor()` RPC). Absent when
 * the call failed — never a stale bind-time value (principle 4).
 */
eventCursor?: (EventCursor | null)
health: SessionHealthSnapshot
/**
 * `lockfile.device.platform`; absent when the assembly layer did
 * not supply it (the SPI attestation does not carry it).
 */
platform?: (string | null)
/**
 * Known session generations, best-effort: the checkpoint-known
 * lineage plus the live session observed at capture.
 */
sessionLineage: string[]
}
/**
 * The attested capability baseline at capture.
 */
export interface AttestationSnapshot {
/**
 * Attestation timestamp, verbatim.
 */
attestedAt: string
/**
 * Digest of the attested lockfile.
 */
lockfileDigest: string
}
/**
 * Event-log cursor of the bound provider session (spine §6.6; advanced
 * ack-after-persist, never across session generations).
 */
export interface EventCursor {
/**
 * Last sequence durably consumed from that session.
 */
lastSequence: number
/**
 * The provider session that issued the recorded events.
 */
sessionId: string
}
/**
 * `ProviderSession::health()` at capture; a failed call records
 * `{ ok: false, degraded: "<errorClass>" }`.
 */
export interface SessionHealthSnapshot {
/**
 * Degradation note (an error class when the health call failed).
 */
degraded?: (string | null)
/**
 * Whether the session answered healthy.
 */
ok: boolean
}
/**
 * One handler trigger against this instance.
 */
export interface HandlerTriggerView {
/**
 * Wall clock.
 */
atMs: number
/**
 * The consulted binding's declared disposition head (03 §1.8
 * closed set; 08 §2.5 handler row). Absent on pre-incorporation
 * ledgers.
 */
disposition?: (string | null)
/**
 * The hook.
 */
hook: string
/**
 * Ledger seq.
 */
seq: number
/**
 * Trigger ordinal.
 */
trigger: number
}
/**
 * `kind: "action"` — fixed pipeline `preflight? → act → observe → assert`.
 */
export interface ActionStepIR {
/**
 * Post-hoc assertions. Empty array ⇒ this step yields no verdict.
 */
assertions: AssertionIR[]
binding: ActionBinding
/**
 * Whether to materialize a checkpoint at this step boundary. Required
 * because sealed IR materializes all defaulted fields
 * (single-representation rule; default true, false inside macro
 * expansions).
 */
checkpoint: boolean
/**
 * `mutating | readonly` (`pure` is excluded — it belongs to `let`).
 */
effect: ("mutating" | "readonly")
/**
 * Canonical hash of "what this step does to the world" (02 §12.3).
 */
effectHash: string
/**
 * Step-level handler hooks; override flow-level ones.
 * 
 * @minItems 1
 */
handlers?: ([HandlerBinding, ...(HandlerBinding)[]] | null)
/**
 * Author-declared idempotence (materialized default: false). Governs
 * timed-out auto-retry and reconcile-uncertain replay permission.
 */
idempotent: boolean
/**
 * Canonical hash of "how this step is judged" (02 §12.3).
 */
judgeHash: string
/**
 * Const `"action"`.
 */
kind: "action"
/**
 * Data contract of the projected output, for downstream static checks.
 */
outputSchema?: (JsonSchemaDocument | null)
/**
 * Output projection: `Record<name, Expr>` over `ActionResult.output` /
 * observation metadata. Self-refs inside refer to the *raw* output
 * (02 §4.1.1). Absent ⇒ identity projection.
 */
outputs?: (ExprMap1 | null)
/**
 * Pre-entry world probes; double as resume drift detection
 * (spine §6.7-C). Distinct from post-hoc `assertions` (`expect`).
 * 
 * @minItems 1
 */
preflight?: ([AssertionIR, ...(AssertionIR)[]] | null)
/**
 * Retry policy — applies to the act phase only (spine §6.5 mount 1).
 */
retry?: (RetryPolicy1 | null)
/**
 * Author-provided, flow-unique, stable step identity.
 */
stepId: string
/**
 * Step budget in milliseconds.
 */
timeoutMs?: (number | null)
/**
 * Canonical verb — pure metadata for reports; the runner has no verb
 * switch (spine R7).
 */
verb?: (CanonicalVerb | null)
}
/**
 * The element to check.
 */
export interface ElementSelectorIR {
/**
 * UI context scoping (native/web, optional context id).
 */
context?: ({
/**
 * Optional concrete context id.
 */
contextId?: (string | null)
/**
 * Context kind (`native` | `web`).
 */
contextKind: ("native" | "web")
} | null)
/**
 * CSS selector (web contexts).
 */
css?: (string | null)
/**
 * Stable identifier (resource id / test id).
 */
identifier?: (string | null)
/**
 * Accessible name.
 */
name?: (string | null)
/**
 * Accessibility role.
 */
role?: (string | null)
/**
 * Text content match.
 */
text?: (TextMatchIR | null)
/**
 * Current value match.
 */
value?: (string | null)
}
/**
 * Text matcher (isomorphic to DeviceRail `TextMatch`).
 * 
 * `mode` and `caseSensitive` are required because sealed IR materializes
 * defaults (`exact` / `false`) — the single-representation rule (02 §2.4).
 */
export interface TextMatchIR {
/**
 * Case sensitivity (materialized default: `false`).
 */
caseSensitive: boolean
/**
 * Match mode (materialized default: `exact`).
 */
mode: ("exact" | "contains")
/**
 * The text to match.
 */
value: string
}
/**
 * Text matcher (isomorphic to DeviceRail `TextMatch`).
 * 
 * `mode` and `caseSensitive` are required because sealed IR materializes
 * defaults (`exact` / `false`) — the single-representation rule (02 §2.4).
 */
export interface TextMatchIR1 {
/**
 * Case sensitivity (materialized default: `false`).
 */
caseSensitive: boolean
/**
 * Match mode (materialized default: `exact`).
 */
mode: ("exact" | "contains")
/**
 * The text to match.
 */
value: string
}
/**
 * The element to check.
 */
export interface ElementSelectorIR1 {
/**
 * UI context scoping (native/web, optional context id).
 */
context?: ({
/**
 * Optional concrete context id.
 */
contextId?: (string | null)
/**
 * Context kind (`native` | `web`).
 */
contextKind: ("native" | "web")
} | null)
/**
 * CSS selector (web contexts).
 */
css?: (string | null)
/**
 * Stable identifier (resource id / test id).
 */
identifier?: (string | null)
/**
 * Accessible name.
 */
name?: (string | null)
/**
 * Accessibility role.
 */
role?: (string | null)
/**
 * Text content match.
 */
text?: (TextMatchIR | null)
/**
 * Current value match.
 */
value?: (string | null)
}
/**
 * Literal JSON value.
 */
export interface LitExpr {
/**
 * The literal value, verbatim.
 */
lit: unknown
}
/**
 * Reference into the closed scope grammar.
 */
export interface RefExpr {
/**
 * The dotted reference path.
 */
ref: string
}
/**
 * Rectangular region, field-compatible with DeviceRail `UiRect`.
 * 
 * Uses `serde_json::Number` (not `f64`) so integer inputs round-trip as
 * integers — required by the canonical-form rule that numbers keep their
 * shortest ES representation (02 §12.1).
 */
export interface RectIR {
/**
 * Height (≥ 0).
 */
height: number
/**
 * Width (≥ 0).
 */
width: number
/**
 * X origin.
 */
x: number
/**
 * Y origin.
 */
y: number
}
/**
 * The compile-time fully bound act-chain.
 */
export interface ActionBinding {
/**
 * The attempts, in declared order. A subsequent attempt is tried only
 * after `action_failed_final` of the previous one (spine §6.2).
 * 
 * @minItems 1
 */
attempts: [BoundAttempt, ...(BoundAttempt)[]]
}
/**
 * One fully bound attempt of the act-chain (02 §5.1).
 * 
 * `protection` is const `"standard"` in v0.1: bind rejects protected
 * actions (spine R6). `coordinate` attempts must carry literal static
 * coordinates in `args` (bind-phase check).
 */
export interface BoundAttempt {
/**
 * Whitelist of daemon-internal execution modes (spine §6.4 R-degrade).
 * Derived per attempt from its own `channel` only; semantic attempts
 * never include `coordinateFallback`. Set semantics — serialized in
 * declaration order of [`ExecutionMode`], deduplicated on load.
 * 
 * @minItems 1
 */
acceptExecutionModes: [ExecutionMode, ...(ExecutionMode)[]]
/**
 * Provider-native action name (per lockfile.device.actions).
 */
actionName: string
args: ExprMap
/**
 * Locating channel — [`ActChannel`], so `vision` is structurally
 * impossible here (principle 7).
 */
channel: ("dom" | "uiTree" | "coordinate")
/**
 * Const `"standard"` in v0.1 (spine R6).
 */
protection: "standard"
/**
 * Feature this attempt depends on (e.g. `device.semanticActions.v1`).
 */
requiresFeature?: (FeatureId | null)
}
/**
 * Arguments as expressions; shape-checked against the action's
 * `inputSchema` at bind time and re-checked after evaluation at runtime.
 */
export interface ExprMap {
[k: string]: Expr
}
/**
 * A handler mounted on a hook.
 * 
 * The `errorClasses` filter is legal only on `onError` — the baseline
 * `if`/`else` conditional is reproduced via `#[schemars(extend)]`.
 */
export interface HandlerBinding {
/**
 * What to do when the hook fires.
 */
action: ({
kind: "retry"
policy: RetryPolicy
} | {
kind: "continue"
} | {
human: HumanStepIR
kind: "escalate"
} | {
kind: "abort"
} | {
flowRef: FlowRef
kind: "repair"
})
/**
 * Error-class filter — only meaningful (and only legal) on `onError`.
 * 
 * @minItems 1
 */
errorClasses?: ([ErrorClass, ...(ErrorClass)[]] | null)
/**
 * The hook this handler fires on.
 */
hook: ("onFail" | "onUnknown" | "onError" | "onResumeDrift")
/**
 * Trigger budget (loop guard).
 */
maxTriggers: number
}
/**
 * The retry policy for the re-entry.
 */
export interface RetryPolicy {
/**
 * Backoff: fixed milliseconds or an exponential schedule.
 */
backoffMs: (number | {
/**
 * Multiplication factor (≥ 1).
 */
factor: number
/**
 * Initial delay in milliseconds (≥ 0).
 */
initial: number
/**
 * Delay ceiling in milliseconds (≥ 0).
 */
max: number
})
/**
 * Attempt budget (≥ 1).
 */
maxAttempts: number
/**
 * Which error classes are retryable here. Semantically meaningful:
 * `action_failed_retryable`, `target_stale` (forces re-observe), and —
 * for idempotent steps — `action_timed_out`; `check` warns on the rest.
 * Set semantics — serialized in [`ErrorClass`] declaration order.
 * 
 * @minItems 1
 */
retryOn: [ErrorClass, ...(ErrorClass)[]]
}
/**
 * The embedded human step (boxed: much larger than sibling variants).
 */
export interface HumanStepIR {
/**
 * Whether to materialize a checkpoint at this step boundary. Required
 * because sealed IR materializes all defaulted fields
 * (single-representation rule; default true, false inside macro
 * expansions).
 */
checkpoint: boolean
/**
 * Enumerated options for judge/confirm modes.
 * 
 * @minItems 1
 */
decisions?: ([string, ...(string)[]] | null)
/**
 * Canonical hash of "what this step does to the world" (02 §12.3).
 */
effectHash: string
/**
 * Step-level handler hooks; override flow-level ones.
 * 
 * @minItems 1
 */
handlers?: ([HandlerBinding, ...(HandlerBinding)[]] | null)
/**
 * Canonical hash of "how this step is judged" (02 §12.3).
 */
judgeHash: string
/**
 * Const `"human"`.
 */
kind: "human"
/**
 * Interaction mode.
 */
mode: ("confirm" | "judge" | "provideInput" | "repairWorld")
/**
 * Const `"unknown"` (principle 4).
 */
onTimeout: "unknown"
/**
 * Input contract for `provideInput` mode (required there, schema-enforced).
 */
outputSchema?: (JsonSchemaDocument | null)
/**
 * Pre-entry world probes; double as resume drift detection
 * (spine §6.7-C). Distinct from post-hoc `assertions` (`expect`).
 * 
 * @minItems 1
 */
preflight?: ([AssertionIR, ...(AssertionIR)[]] | null)
/**
 * Evidence/values presented to the human (expressions).
 */
presents: Expr[]
/**
 * The question posed to the human.
 */
prompt: string
/**
 * Retry policy — applies to the act phase only (spine §6.5 mount 1).
 */
retry?: (RetryPolicy1 | null)
/**
 * Author-provided, flow-unique, stable step identity.
 */
stepId: string
/**
 * Required budget; expiry yields verdict `unknown`.
 */
timeoutMs: number
}
/**
 * Retry policy. Applies to the act phase only (spine §6.5 mount point 1);
 * each retry mints a new `callId` and a new `actionIntent` WAL record.
 */
export interface RetryPolicy1 {
/**
 * Backoff: fixed milliseconds or an exponential schedule.
 */
backoffMs: (number | {
/**
 * Multiplication factor (≥ 1).
 */
factor: number
/**
 * Initial delay in milliseconds (≥ 0).
 */
initial: number
/**
 * Delay ceiling in milliseconds (≥ 0).
 */
max: number
})
/**
 * Attempt budget (≥ 1).
 */
maxAttempts: number
/**
 * Which error classes are retryable here. Semantically meaningful:
 * `action_failed_retryable`, `target_stale` (forces re-observe), and —
 * for idempotent steps — `action_timed_out`; `check` warns on the rest.
 * Set semantics — serialized in [`ErrorClass`] declaration order.
 * 
 * @minItems 1
 */
retryOn: [ErrorClass, ...(ErrorClass)[]]
}
/**
 * The repair subflow, pinned like a `call`.
 */
export interface FlowRef {
/**
 * The callee's flow id.
 */
flowId: string
/**
 * The callee's content hash (integrity pin; runner verifies on load).
 */
irHash: string
}
/**
 * Identifier-keyed map of expressions (exemption class 2: keys are data, constrained by propertyNames).
 */
export interface ExprMap1 {
[k: string]: Expr
}
/**
 * `kind: "assert"` — side-effect-free observation and judgment.
 */
export interface AssertStepIR {
/**
 * At least one assertion (an assertion-free assert step is meaningless).
 * 
 * @minItems 1
 */
assertions: [AssertionIR, ...(AssertionIR)[]]
/**
 * Whether to materialize a checkpoint at this step boundary. Required
 * because sealed IR materializes all defaulted fields
 * (single-representation rule; default true, false inside macro
 * expansions).
 */
checkpoint: boolean
/**
 * Canonical hash of "what this step does to the world" (02 §12.3).
 */
effectHash: string
/**
 * Step-level handler hooks; override flow-level ones.
 * 
 * @minItems 1
 */
handlers?: ([HandlerBinding, ...(HandlerBinding)[]] | null)
/**
 * Canonical hash of "how this step is judged" (02 §12.3).
 */
judgeHash: string
/**
 * Const `"assert"`.
 */
kind: "assert"
/**
 * Observation source: fresh capture or reuse of an action step's
 * before/after observation (offline re-judgeable).
 */
observe: ("fresh" | {
/**
 * The action step whose observation is reused.
 */
fromStep: string
/**
 * Which observation (`after` | `before`).
 */
which: ("after" | "before")
})
/**
 * Pre-entry world probes; double as resume drift detection
 * (spine §6.7-C). Distinct from post-hoc `assertions` (`expect`).
 * 
 * @minItems 1
 */
preflight?: ([AssertionIR, ...(AssertionIR)[]] | null)
/**
 * Retry policy — applies to the act phase only (spine §6.5 mount 1).
 */
retry?: (RetryPolicy1 | null)
/**
 * Author-provided, flow-unique, stable step identity.
 */
stepId: string
/**
 * Step budget in milliseconds.
 */
timeoutMs?: (number | null)
}
/**
 * `kind: "call"` — subflow invocation, pinned by content hash.
 */
export interface CallStepIR {
/**
 * Whether to materialize a checkpoint at this step boundary. Required
 * because sealed IR materializes all defaulted fields
 * (single-representation rule; default true, false inside macro
 * expansions).
 */
checkpoint: boolean
/**
 * Canonical hash of "what this step does to the world" (02 §12.3).
 */
effectHash: string
flowRef: FlowRef1
/**
 * Step-level handler hooks; override flow-level ones.
 * 
 * @minItems 1
 */
handlers?: ([HandlerBinding, ...(HandlerBinding)[]] | null)
inputs: ExprMap2
/**
 * Canonical hash of "how this step is judged" (02 §12.3).
 */
judgeHash: string
/**
 * Const `"call"`.
 */
kind: "call"
/**
 * Pre-entry world probes; double as resume drift detection
 * (spine §6.7-C). Distinct from post-hoc `assertions` (`expect`).
 * 
 * @minItems 1
 */
preflight?: ([AssertionIR, ...(AssertionIR)[]] | null)
/**
 * Retry policy — applies to the act phase only (spine §6.5 mount 1).
 */
retry?: (RetryPolicy1 | null)
/**
 * Author-provided, flow-unique, stable step identity.
 */
stepId: string
/**
 * Step budget in milliseconds.
 */
timeoutMs?: (number | null)
}
/**
 * The callee, pinned by `flowId` + `irHash`.
 */
export interface FlowRef1 {
/**
 * The callee's flow id.
 */
flowId: string
/**
 * The callee's content hash (integrity pin; runner verifies on load).
 */
irHash: string
}
/**
 * Identifier-keyed map of expressions (exemption class 2: keys are data, constrained by propertyNames).
 */
export interface ExprMap2 {
[k: string]: Expr
}
/**
 * `kind: "human"` — human collaboration node (principle 8).
 */
export interface HumanStepIR1 {
/**
 * Whether to materialize a checkpoint at this step boundary. Required
 * because sealed IR materializes all defaulted fields
 * (single-representation rule; default true, false inside macro
 * expansions).
 */
checkpoint: boolean
/**
 * Enumerated options for judge/confirm modes.
 * 
 * @minItems 1
 */
decisions?: ([string, ...(string)[]] | null)
/**
 * Canonical hash of "what this step does to the world" (02 §12.3).
 */
effectHash: string
/**
 * Step-level handler hooks; override flow-level ones.
 * 
 * @minItems 1
 */
handlers?: ([HandlerBinding, ...(HandlerBinding)[]] | null)
/**
 * Canonical hash of "how this step is judged" (02 §12.3).
 */
judgeHash: string
/**
 * Const `"human"`.
 */
kind: "human"
/**
 * Interaction mode.
 */
mode: ("confirm" | "judge" | "provideInput" | "repairWorld")
/**
 * Const `"unknown"` (principle 4).
 */
onTimeout: "unknown"
/**
 * Input contract for `provideInput` mode (required there, schema-enforced).
 */
outputSchema?: (JsonSchemaDocument | null)
/**
 * Pre-entry world probes; double as resume drift detection
 * (spine §6.7-C). Distinct from post-hoc `assertions` (`expect`).
 * 
 * @minItems 1
 */
preflight?: ([AssertionIR, ...(AssertionIR)[]] | null)
/**
 * Evidence/values presented to the human (expressions).
 */
presents: Expr[]
/**
 * The question posed to the human.
 */
prompt: string
/**
 * Retry policy — applies to the act phase only (spine §6.5 mount 1).
 */
retry?: (RetryPolicy1 | null)
/**
 * Author-provided, flow-unique, stable step identity.
 */
stepId: string
/**
 * Required budget; expiry yields verdict `unknown`.
 */
timeoutMs: number
}
/**
 * `kind: "if"` — conditional container.
 */
export interface IfStepIR {
/**
 * Whether to materialize a checkpoint at this step boundary. Required
 * because sealed IR materializes all defaulted fields
 * (single-representation rule; default true, false inside macro
 * expansions).
 */
checkpoint: boolean
/**
 * Expression node: exactly one of `lit` / `ref` / `fn` (02 §8.1).
 * 
 * Wire shape is the baseline schema's `oneOf` of three closed single-key
 * objects; the variants are mutually exclusive by their required keys, so
 * serde's untagged representation is deterministic.
 */
cond: (LitExpr | RefExpr | FnExpr)
/**
 * Canonical hash of "what this step does to the world" (02 §12.3).
 */
effectHash: string
/**
 * Steps executed otherwise (≥ 1 when present). Unselected branch steps
 * are `skipped`.
 * 
 * @minItems 1
 */
else?: ([StepIR, ...(StepIR)[]] | null)
/**
 * Step-level handler hooks; override flow-level ones.
 * 
 * @minItems 1
 */
handlers?: ([HandlerBinding, ...(HandlerBinding)[]] | null)
/**
 * Canonical hash of "how this step is judged" (02 §12.3).
 */
judgeHash: string
/**
 * Const `"if"`.
 */
kind: "if"
/**
 * Pre-entry world probes; double as resume drift detection
 * (spine §6.7-C). Distinct from post-hoc `assertions` (`expect`).
 * 
 * @minItems 1
 */
preflight?: ([AssertionIR, ...(AssertionIR)[]] | null)
/**
 * Retry policy — applies to the act phase only (spine §6.5 mount 1).
 */
retry?: (RetryPolicy1 | null)
/**
 * Author-provided, flow-unique, stable step identity.
 */
stepId: string
/**
 * Steps executed when the condition holds (≥ 1).
 * 
 * @minItems 1
 */
then: [StepIR, ...(StepIR)[]]
/**
 * Step budget in milliseconds.
 */
timeoutMs?: (number | null)
}
/**
 * `kind: "foreach"` — iteration container.
 */
export interface ForeachStepIR {
/**
 * Iteration variable name (scoped as `iter.<as>`).
 */
as: string
/**
 * Loop body (≥ 1 step).
 * 
 * @minItems 1
 */
body: [StepIR, ...(StepIR)[]]
/**
 * Whether to materialize a checkpoint at this step boundary. Required
 * because sealed IR materializes all defaulted fields
 * (single-representation rule; default true, false inside macro
 * expansions).
 */
checkpoint: boolean
/**
 * Canonical hash of "what this step does to the world" (02 §12.3).
 */
effectHash: string
/**
 * Step-level handler hooks; override flow-level ones.
 * 
 * @minItems 1
 */
handlers?: ([HandlerBinding, ...(HandlerBinding)[]] | null)
/**
 * Expression node: exactly one of `lit` / `ref` / `fn` (02 §8.1).
 * 
 * Wire shape is the baseline schema's `oneOf` of three closed single-key
 * objects; the variants are mutually exclusive by their required keys, so
 * serde's untagged representation is deterministic.
 */
items: (LitExpr | RefExpr | FnExpr)
/**
 * Canonical hash of "how this step is judged" (02 §12.3).
 */
judgeHash: string
/**
 * Const `"foreach"`.
 */
kind: "foreach"
/**
 * Pre-entry world probes; double as resume drift detection
 * (spine §6.7-C). Distinct from post-hoc `assertions` (`expect`).
 * 
 * @minItems 1
 */
preflight?: ([AssertionIR, ...(AssertionIR)[]] | null)
/**
 * Retry policy — applies to the act phase only (spine §6.5 mount 1).
 */
retry?: (RetryPolicy1 | null)
/**
 * Author-provided, flow-unique, stable step identity.
 */
stepId: string
/**
 * Step budget in milliseconds.
 */
timeoutMs?: (number | null)
}
/**
 * `kind: "let"` — pure bindings into `vars.*` (SSA).
 */
export interface LetStepIR {
/**
 * The bindings (≥ 1 entry).
 */
bindings: ExprMap1
/**
 * Whether to materialize a checkpoint at this step boundary. Required
 * because sealed IR materializes all defaulted fields
 * (single-representation rule; default true, false inside macro
 * expansions).
 */
checkpoint: boolean
/**
 * Canonical hash of "what this step does to the world" (02 §12.3).
 */
effectHash: string
/**
 * Step-level handler hooks; override flow-level ones.
 * 
 * @minItems 1
 */
handlers?: ([HandlerBinding, ...(HandlerBinding)[]] | null)
/**
 * Canonical hash of "how this step is judged" (02 §12.3).
 */
judgeHash: string
/**
 * Const `"let"`.
 */
kind: "let"
/**
 * Pre-entry world probes; double as resume drift detection
 * (spine §6.7-C). Distinct from post-hoc `assertions` (`expect`).
 * 
 * @minItems 1
 */
preflight?: ([AssertionIR, ...(AssertionIR)[]] | null)
/**
 * Retry policy — applies to the act phase only (spine §6.5 mount 1).
 */
retry?: (RetryPolicy1 | null)
/**
 * Author-provided, flow-unique, stable step identity.
 */
stepId: string
/**
 * Step budget in milliseconds.
 */
timeoutMs?: (number | null)
}
/**
 * A localized observation record (spine §6.6; omissions are typed data).
 */
export interface ObservationRecord {
/**
 * Capture timestamp (ms since epoch).
 */
capturedAtMs: number
/**
 * Provider-scoped observation id.
 */
observationId: string
/**
 * Localized screenshot evidence, when captured.
 */
screenshot?: (EvidenceRef | null)
/**
 * Why the screenshot was legitimately omitted.
 */
screenshotOmission?: (ScreenshotOmissionReason | null)
/**
 * Localized UI-tree evidence, when captured.
 */
uiSnapshot?: (EvidenceRef | null)
/**
 * Why the UI snapshot was legitimately omitted.
 */
uiSnapshotOmission?: (UiSnapshotOmissionReason | null)
/**
 * The capture-time viewport, verbatim from the provider observation
 * (M3a additive close of the registered W1 gap; absent on ledgers
 * recorded before the field existed, or when the provider reported
 * a non-finite scale factor — the runner refuses to persist a value
 * serde_json would write as `null` and never read back).
 * 
 * Compat note: the additive claim is one-directional — readers
 * built before this field existed reject ledgers containing it
 * (`deny_unknown_fields`, fail-closed per R12); binary downgrade
 * against a store written by a newer runner is unsupported.
 */
viewport?: (Viewport | null)
}
/**
 * A localized evidence entry: the provider [`AssetRef`] plus the local
 * content-addressed copy (spine §6.6 — evidence is localized during
 * `observing` because provider-side retention is not guaranteed).
 */
export interface EvidenceRef {
asset: AssetRef3
/**
 * Path inside the store's content-addressed evidence area.
 */
localPath: string
/**
 * Bare lowercase hex sha256 digest of the localized bytes.
 */
sha256: string
}
/**
 * Content-addressed evidence reference (DeviceRail `AssetRef`, spine A.8).
 * Never inline bytes; `sha256` is the bare hex digest when present.
 */
export interface AssetRef3 {
/**
 * Provider-scoped asset id (e.g. `sha256:<digest>` or an opaque id).
 */
id: string
/**
 * Media type, e.g. `image/png`.
 */
mediaType: string
/**
 * Bare lowercase hex sha256 digest of the content, when known.
 */
sha256?: (string | null)
/**
 * Provider URI, e.g. `devicerail://assets/sha256/<digest>`.
 */
uri: string
}
/**
 * Viewport of an observation (DeviceRail `Viewport`).
 */
export interface Viewport {
/**
 * Height in device-independent pixels.
 */
height: number
/**
 * Device scale factor.
 */
scaleFactor: number
/**
 * Width in device-independent pixels.
 */
width: number
}
/**
 * YAML source location resolved through the sourceMap (07 §2.3 part 2).
 */
export interface SourceLocation {
entry: SourceMapEntry
/**
 * JSON Pointer of the IR node inside its `FlowIR`.
 */
irPath: string
}
/**
 * The sourceMap entry: file + span + macro origin trace.
 */
export interface SourceMapEntry {
/**
 * The YAML source file.
 */
file: string
/**
 * RFC 6901 JSON Pointer into this FlowIR document.
 */
irPath: string
/**
 * Macro expansion chain, innermost first. Present iff the IR node was
 * produced by macro expansion — the only structural residue macros
 * leave in the IR (02 §7).
 * 
 * @minItems 1
 */
origin?: ([MacroOriginFrame, ...(MacroOriginFrame)[]] | null)
span: SourceSpan1
}
/**
 * One frame of a macro expansion chain.
 */
export interface MacroOriginFrame {
/**
 * The file containing the expansion site.
 */
file: string
/**
 * The macro's name.
 */
macro: string
span: SourceSpan
}
/**
 * The span of the expansion site.
 */
export interface SourceSpan {
/**
 * End column (1-based).
 */
endCol: number
/**
 * End line (1-based).
 */
endLine: number
/**
 * Start column (1-based).
 */
startCol: number
/**
 * Start line (1-based).
 */
startLine: number
}
/**
 * The source span.
 */
export interface SourceSpan1 {
/**
 * End column (1-based).
 */
endCol: number
/**
 * End line (1-based).
 */
endLine: number
/**
 * Start column (1-based).
 */
startCol: number
/**
 * Start line (1-based).
 */
startLine: number
}
/**
 * The durable per-step verdict projection stored in `StepRecord`
 * (spine §6.6 — the folded summary/evidence live in the RunLog's
 * `verdictRecorded` payload; the record keeps the alignment-relevant core).
 */
export interface StepVerdict {
/**
 * Degradation flag (see [`Verdict::degraded`]).
 */
degraded: boolean
/**
 * Three-valued status.
 */
status: ("pass" | "fail" | "unknown")
/**
 * Id of the superseded verdict, for re-judgement lineage.
 */
supersedes?: (string | null)
}
/**
 * One recorded verdict in the append-only lineage (re-judgements
 * append with `supersedes`; history is never deleted — 08 §2.5).
 */
export interface VerdictRecordView {
/**
 * Wall clock of the record.
 */
atMs: number
/**
 * Typed localization failures of the same judgment (payload
 * mirror — the seq-bearing aggregate lives on the dossier).
 */
localizationGaps?: EvidenceGap[]
/**
 * This judgment's localized settlement/verdict/human evidence
 * (item ③, 2026-07-18); empty on offline re-judgements and
 * pre-incorporation records.
 */
localized?: EvidenceRef[]
/**
 * Ledger seq of the `verdictRecorded` event.
 */
seq: number
verdict: Verdict
}
/**
 * A typed failed-localization record (2026-07-18 incorporation, item ③):
 * the declared asset plus why its bytes could not be localized. Gaps are
 * data, never silent omissions (principle 4/R4).
 */
export interface EvidenceGap {
asset: AssetRef4
/**
 * Why localization failed.
 */
reason: string
}
/**
 * Content-addressed evidence reference (DeviceRail `AssetRef`, spine A.8).
 * Never inline bytes; `sha256` is the bare hex digest when present.
 */
export interface AssetRef4 {
/**
 * Provider-scoped asset id (e.g. `sha256:<digest>` or an opaque id).
 */
id: string
/**
 * Media type, e.g. `image/png`.
 */
mediaType: string
/**
 * Bare lowercase hex sha256 digest of the content, when known.
 */
sha256?: (string | null)
/**
 * Provider URI, e.g. `devicerail://assets/sha256/<digest>`.
 */
uri: string
}
/**
 * The full verdict as recorded.
 */
export interface Verdict {
/**
 * Whether the pass rests on a degraded verify channel or an
 * unauthorized provider-internal fallback (spine §6.3/§6.4).
 */
degraded: boolean
/**
 * Evidence citations (provider write path caps at 64, spine §4.2).
 */
evidence: AssetRef[]
/**
 * Three-valued status (unknown never folds to pass).
 */
status: ("pass" | "fail" | "unknown")
/**
 * Human-readable folding summary (provider write path caps this at
 * 16384 chars, spine §4.2).
 */
summary: string
/**
 * Id of the verdict this one supersedes, for re-judgement lineage.
 */
supersedes?: (string | null)
}
