//! Phase 5 `seal`: bound tree → `FlowIR` + binding report (spine §8
//! stage 5, 03 §4.2).
//!
//! Seal has no rejection conditions for a legal tree — every refusal
//! happened in the four phases before it; seal only stamps: canonical
//! assembly (recursively over `if`/`foreach` subtrees), per-step
//! `effectHash`/`judgeHash` (handler-embedded escalate human steps
//! included), whole-tree `irHash`, `sourceMap` (one entry per body-tree
//! step: IR JSON Pointer + YAML span + macro origin chain), the
//! `subflows` registry (call + repair pins) and the embedded
//! `lockfileDigest`.
//!
//! The one check that *can* fire here is the factory self-check: the
//! sealed artifact must validate against the schema generated by
//! `pointlock_ir::schema_gen` (R12). A failure is a compiler bug surfaced
//! as [`codes::INTERNAL_FACTORY_CHECK`], never an authoring error.

use std::collections::BTreeMap;
use std::sync::OnceLock;

use pointlock_ir::vocab::CanonicalVerb;
use pointlock_ir::{
    ActionBinding, ActionStepIR, AssertStepIR, CallStepIR, ExprMap, FlowIR, FlowId, FlowRef,
    ForeachStepIR, HandlerAction, HandlerBinding, Hash, HumanStepIR, IfStepIR, IrVersion,
    JsonPointer, LetStepIR, ObservationSource, OnTimeout, OutputDecl, ParamDecl, ProviderName,
    ProviderRef, SourceMapEntry, StepBase, StepIR, effect_hash, ir_hash, judge_hash, schema_gen,
};

use crate::bind::{BindingReport, BoundFlow, BoundStep, BoundStepKind};
use crate::check::{
    CheckedHandler, CheckedHandlerAction, CheckedHead, CheckedHuman, CheckedStep, CheckedStepKind,
};
use crate::diagnostic::{CompileDiagnostic, codes};

/// The sealed compilation product.
#[derive(Debug, Clone)]
pub struct Sealed {
    /// The compiled, content-addressed flow artifact.
    pub flow_ir: FlowIR,
    /// The human-reviewable binding report (03 §4.5 confirmation point 3).
    pub binding_report: BindingReport,
    /// Warnings carried through a successful compile (03 §4.3 F6 — e.g.
    /// the R13 default-escalation lint). Never contains errors.
    pub warnings: Vec<CompileDiagnostic>,
    /// The compiled callee closure (every subflow linked by `call` or
    /// `repair`, content-keyed). Populated by the top-level [`crate::compile`]
    /// entry; empty for flows without subflows and for nested compiles.
    pub subflow_irs: std::collections::BTreeMap<Hash, FlowIR>,
}

fn placeholder_hash() -> Hash {
    Hash::new(format!("sha256:{}", "0".repeat(64)))
        .expect("the all-zero digest is always grammatical")
}

/// Mutable access to a step's common envelope (hash stamping).
fn base_mut(step: &mut StepIR) -> &mut StepBase {
    match step {
        StepIR::Action(s) => &mut s.base,
        StepIR::Assert(s) => &mut s.base,
        StepIR::Call(s) => &mut s.base,
        StepIR::Human(s) => &mut s.base,
        StepIR::If(s) => &mut s.base,
        StepIR::Foreach(s) => &mut s.base,
        StepIR::Let(s) => &mut s.base,
    }
}

/// Computes and stamps the dual hashes; the stored (placeholder) values
/// are ignored by the hash functions (02 §12.3).
fn stamp_hashes(step: &mut StepIR) {
    let (effect, judge) = (effect_hash(step), judge_hash(step));
    let base = base_mut(step);
    base.effect_hash = effect;
    base.judge_hash = judge;
}

/// Assembles and stamps the artifact.
pub(crate) fn seal(
    bound: BoundFlow,
    source_name: &str,
    warnings: Vec<CompileDiagnostic>,
) -> Result<Sealed, Vec<CompileDiagnostic>> {
    let BoundFlow {
        checked,
        steps: bound_steps,
        required_features,
        lockfile_digest,
        provider_version,
        report,
    } = bound;

    let mut subflows: BTreeMap<FlowId, FlowRef> = BTreeMap::new();
    let handlers = seal_handlers(checked.handlers, &mut subflows);

    let mut body = Vec::new();
    let mut source_map = Vec::new();
    for (index, (step, bound_step)) in checked.steps.into_iter().zip(bound_steps).enumerate() {
        body.push(seal_step(
            step,
            bound_step,
            format!("/body/{index}"),
            source_name,
            &mut source_map,
            &mut subflows,
        ));
    }

    let mut flow_ir = FlowIR {
        ir_version: IrVersion,
        flow_id: checked.flow_id,
        ir_hash: placeholder_hash(),
        provider: ProviderRef {
            name: ProviderName::Value,
            version: provider_version,
        },
        required_features,
        lockfile_digest,
        params: checked
            .params
            .into_iter()
            .map(|param| ParamDecl {
                name: param.name,
                schema: param.schema,
                required: param.required,
                default: param.default,
            })
            .collect(),
        outputs: checked
            .outputs
            .into_iter()
            .map(|output| OutputDecl {
                name: output.name,
                schema: output.schema,
                from: output.from,
            })
            .collect(),
        body,
        handlers,
        verdict_policy: checked.verdict_policy,
        source_map,
        subflows,
    };
    // irHash excludes itself and sourceMap; the stored value is ignored
    // during computation (02 §12.2).
    flow_ir.ir_hash = ir_hash(&flow_ir);

    factory_check(&flow_ir)?;
    Ok(Sealed {
        flow_ir,
        binding_report: report,
        warnings,
        subflow_irs: std::collections::BTreeMap::new(),
    })
}

/// Seals one step (recursively for containers): builds the wire form,
/// records its source-map entry (pre-order; macro origin chain attached)
/// and stamps the dual hashes. Container hashes exclude their subtrees by
/// construction of the hash field domains (02 §12.3 item 5).
fn seal_step(
    step: CheckedStep,
    bound: BoundStep,
    ir_path: String,
    file: &str,
    source_map: &mut Vec<SourceMapEntry>,
    subflows: &mut BTreeMap<FlowId, FlowRef>,
) -> StepIR {
    source_map.push(SourceMapEntry {
        ir_path: JsonPointer::new(ir_path.clone())
            .expect("seal-composed JSON Pointers are always grammatical"),
        file: file.to_owned(),
        span: step.span.to_ir(),
        origin: (!step.origin.is_empty()).then_some(step.origin),
    });

    let base = StepBase {
        step_id: step.step_id,
        effect_hash: placeholder_hash(),
        judge_hash: placeholder_hash(),
        preflight: (!bound.preflight.is_empty()).then_some(bound.preflight),
        retry: step.retry,
        timeout_ms: step.timeout_ms,
        handlers: seal_handlers(step.handlers, subflows),
        checkpoint: step.checkpoint,
    };

    let mut step_ir = match (step.kind, bound.kind) {
        (
            CheckedStepKind::Action(action),
            BoundStepKind::Action {
                attempts,
                assertions,
            },
        ) => {
            // Report metadata only — the runner has no verb switch (R7).
            let verb = match &action.head {
                CheckedHead::Invoke { .. } => CanonicalVerb::Invoke,
                CheckedHead::Verb(verb) => verb.verb,
            };
            StepIR::Action(ActionStepIR {
                kind: Default::default(),
                base,
                verb: Some(verb),
                effect: action.effect.expect("bind rejected missing effect"),
                idempotent: action.idempotent,
                binding: ActionBinding { attempts },
                assertions,
                outputs: None,
                output_schema: action.output_schema,
            })
        }
        (CheckedStepKind::Assert { .. }, BoundStepKind::Assert { assertions }) => {
            StepIR::Assert(AssertStepIR {
                kind: Default::default(),
                base,
                observe: ObservationSource::fresh(),
                assertions,
            })
        }
        (CheckedStepKind::Call(call), BoundStepKind::Call) => {
            subflows.insert(call.flow_ref.flow_id.clone(), call.flow_ref.clone());
            StepIR::Call(CallStepIR {
                kind: Default::default(),
                base,
                flow_ref: call.flow_ref,
                inputs: call
                    .inputs
                    .into_iter()
                    .map(|arg| (arg.name, arg.expr))
                    .collect::<ExprMap>(),
            })
        }
        (CheckedStepKind::Human(human), BoundStepKind::Human) => {
            StepIR::Human(seal_human(*human, base))
        }
        (CheckedStepKind::If(if_step), BoundStepKind::If { then, r#else }) => {
            let then_ir = if_step
                .then
                .into_iter()
                .zip(then)
                .enumerate()
                .map(|(index, (child, bound_child))| {
                    seal_step(
                        child,
                        bound_child,
                        format!("{ir_path}/then/{index}"),
                        file,
                        source_map,
                        subflows,
                    )
                })
                .collect();
            let else_ir = if_step.r#else.map(|steps| {
                steps
                    .into_iter()
                    .zip(r#else.expect("bind mirrors the checked tree"))
                    .enumerate()
                    .map(|(index, (child, bound_child))| {
                        seal_step(
                            child,
                            bound_child,
                            format!("{ir_path}/else/{index}"),
                            file,
                            source_map,
                            subflows,
                        )
                    })
                    .collect()
            });
            StepIR::If(IfStepIR {
                kind: Default::default(),
                base,
                cond: if_step.cond,
                then: then_ir,
                r#else: else_ir,
            })
        }
        (CheckedStepKind::Foreach(foreach), BoundStepKind::Foreach { body }) => {
            let body_ir = foreach
                .body
                .into_iter()
                .zip(body)
                .enumerate()
                .map(|(index, (child, bound_child))| {
                    seal_step(
                        child,
                        bound_child,
                        format!("{ir_path}/body/{index}"),
                        file,
                        source_map,
                        subflows,
                    )
                })
                .collect();
            StepIR::Foreach(ForeachStepIR {
                kind: Default::default(),
                base,
                items: foreach.items,
                r#as: foreach.r#as,
                body: body_ir,
            })
        }
        (CheckedStepKind::Let { bindings }, BoundStepKind::Let) => StepIR::Let(LetStepIR {
            kind: Default::default(),
            base,
            bindings: bindings.into_iter().collect::<ExprMap>(),
        }),
        _ => unreachable!("bind mirrors the checked tree kind-for-kind"),
    };

    stamp_hashes(&mut step_ir);
    step_ir
}

/// Builds a `HumanStepIR` from checked human material and a prepared base.
fn seal_human(human: CheckedHuman, base: StepBase) -> HumanStepIR {
    HumanStepIR {
        kind: Default::default(),
        base,
        mode: human.mode,
        prompt: human.prompt,
        presents: human.presents,
        decisions: human.decisions,
        output_schema: human.output_schema,
        timeout_ms: human.timeout_ms,
        on_timeout: OnTimeout::Value,
    }
}

/// Seals a handler list into `HandlerBinding`s: escalate actions embed a
/// hash-stamped human step under its synthesized id (02 §3), repair
/// actions pin their subflow into the registry.
fn seal_handlers(
    handlers: Vec<CheckedHandler>,
    subflows: &mut BTreeMap<FlowId, FlowRef>,
) -> Option<Vec<HandlerBinding>> {
    if handlers.is_empty() {
        return None;
    }
    let bindings = handlers
        .into_iter()
        .map(|handler| {
            let action = match handler.action {
                CheckedHandlerAction::Retry(policy) => HandlerAction::Retry { policy },
                CheckedHandlerAction::Continue => HandlerAction::Continue,
                CheckedHandlerAction::Abort => HandlerAction::Abort,
                CheckedHandlerAction::Repair { flow_ref, .. } => {
                    subflows.insert(flow_ref.flow_id.clone(), flow_ref.clone());
                    HandlerAction::Repair { flow_ref }
                }
                CheckedHandlerAction::Escalate { step_id, human } => {
                    let base = StepBase {
                        step_id,
                        effect_hash: placeholder_hash(),
                        judge_hash: placeholder_hash(),
                        preflight: None,
                        retry: None,
                        timeout_ms: None,
                        handlers: None,
                        // Escalate nodes sit outside macro expansions; the
                        // materialized default applies (02 §3).
                        checkpoint: true,
                    };
                    let mut wrapped = StepIR::Human(seal_human(*human, base));
                    stamp_hashes(&mut wrapped);
                    let StepIR::Human(human_ir) = wrapped else {
                        unreachable!("constructed as a human step");
                    };
                    HandlerAction::Escalate {
                        human: Box::new(human_ir),
                    }
                }
            };
            HandlerBinding {
                hook: handler.hook,
                error_classes: handler.error_classes,
                action,
                max_triggers: handler.max_triggers,
            }
        })
        .collect();
    Some(bindings)
}

/// Validates the sealed artifact against the generated FlowIR schema — the
/// compiler's own outgoing inspection (R12).
fn factory_check(flow_ir: &FlowIR) -> Result<(), Vec<CompileDiagnostic>> {
    static VALIDATOR: OnceLock<jsonschema::Validator> = OnceLock::new();
    let validator = VALIDATOR.get_or_init(|| {
        jsonschema::options()
            .with_draft(jsonschema::Draft::Draft202012)
            .build(&schema_gen::flow_ir_schema())
            .expect("the generated FlowIR schema always compiles")
    });
    let instance = serde_json::to_value(flow_ir).expect("a FlowIR always serializes");
    let failures: Vec<CompileDiagnostic> = validator
        .iter_errors(&instance)
        .map(|err| {
            CompileDiagnostic::error(
                codes::INTERNAL_FACTORY_CHECK,
                format!(
                    "internal compiler error: sealed FlowIR failed schema validation at \
                     {}: {err}",
                    err.instance_path
                ),
                None,
            )
        })
        .collect();
    if failures.is_empty() {
        Ok(())
    } else {
        Err(failures)
    }
}
