/* Generated by scripts/generate.mjs from schema/generated/projection/ —
 * the Rust DTOs in pointlock-store::projection are the truth source
 * (spine §10.2). DO NOT EDIT BY HAND. */
/* Compile-time golden-fixture anchor: each fixture literal must
 * satisfy its generated root type. */

import type { FlowGraphView } from "../src/flow-graph-view.js";
({
  "projectionVersion": 1,
  "flowId": "wifi_toggle",
  "irHash": "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  "nodes": [
    {
      "id": "open_wifi_settings",
      "runPath": "wifi_toggle@aaaaaaaa/open_wifi_settings",
      "kind": "action",
      "verb": "tap",
      "actionName": "tapElement",
      "mutating": true,
      "actChain": [
        "uiTree",
        "coordinate"
      ],
      "assertionCount": 1
    },
    {
      "id": "set_ssid:field",
      "runPath": "wifi_toggle@aaaaaaaa/set_ssid:field",
      "kind": "action",
      "verb": "set_value",
      "actionName": "setElementValue",
      "mutating": true,
      "actChain": [
        "uiTree"
      ],
      "assertionCount": 0
    },
    {
      "id": "wifi_on_visible",
      "runPath": "wifi_toggle@aaaaaaaa/wifi_on_visible",
      "kind": "assert",
      "observe": "fresh",
      "assertions": [
        {
          "assertId": "toggle_enabled",
          "predicate": "elementState",
          "verifyVia": [
            "uiTree",
            "vision"
          ]
        },
        {
          "assertId": "ssid_listed",
          "predicate": "elementText",
          "verifyVia": [
            "uiTree"
          ]
        }
      ]
    },
    {
      "id": "ensure_session",
      "runPath": "wifi_toggle@aaaaaaaa/ensure_session/call→ensure_logged_in@bbbbbbbb",
      "kind": "call",
      "calleeFlowId": "ensure_logged_in",
      "calleeIrHash": "sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
      "inputKeys": [
        "username"
      ]
    },
    {
      "id": "wait_if_passed",
      "runPath": "wifi_toggle@aaaaaaaa/wait_if_passed",
      "kind": "if",
      "cond": "{\"fn\":\"eq\",\"args\":[{\"ref\":\"steps.wifi_on_visible.verdict\"},{\"lit\":\"pass\"}]}",
      "hasElse": false
    },
    {
      "id": "wait_connected",
      "runPath": "wifi_toggle@aaaaaaaa/wait_if_passed/wait_connected",
      "parentId": "wait_if_passed",
      "region": "then",
      "kind": "action",
      "verb": "wait_for",
      "actionName": "waitForElement",
      "mutating": false,
      "actChain": [
        "uiTree"
      ],
      "assertionCount": 1
    },
    {
      "id": "confirm_wifi",
      "runPath": "wifi_toggle@aaaaaaaa/confirm_wifi",
      "kind": "human",
      "mode": "confirm",
      "promptHead": "确认设备已连接到目标 Wi-Fi 网络",
      "timeoutMs": 600000
    },
    {
      "id": "label",
      "runPath": "wifi_toggle@aaaaaaaa/label",
      "kind": "let",
      "bindingKeys": [
        "report_label"
      ]
    }
  ],
  "edges": [
    {
      "kind": "seq",
      "from": "open_wifi_settings",
      "to": "set_ssid:field"
    },
    {
      "kind": "seq",
      "from": "set_ssid:field",
      "to": "wifi_on_visible"
    },
    {
      "kind": "seq",
      "from": "wifi_on_visible",
      "to": "ensure_session"
    },
    {
      "kind": "seq",
      "from": "ensure_session",
      "to": "wait_if_passed"
    },
    {
      "kind": "branch",
      "from": "wait_if_passed",
      "to": "wait_connected",
      "label": "then"
    },
    {
      "kind": "seq",
      "from": "wait_if_passed",
      "to": "confirm_wifi"
    },
    {
      "kind": "seq",
      "from": "confirm_wifi",
      "to": "label"
    }
  ],
  "flowHooks": [
    {
      "hook": "onUnknown",
      "disposition": "escalate",
      "maxTriggers": 1
    }
  ]
}) satisfies FlowGraphView;

import type { TimelinePage } from "../src/run-timeline.js";
({
  "projectionVersion": 1,
  "runId": "run-golden",
  "filter": "all",
  "page": 1,
  "pageSize": 50,
  "revision": 14,
  "total": 14,
  "entries": [
    {
      "seq": 1,
      "atMs": 1010,
      "runPath": "demo@aaaaaaaa",
      "detail": {
        "type": "runStarted",
        "supervisePolicy": null
      },
      "evidence": [],
      "evidenceOmitted": 0,
      "truncated": false
    },
    {
      "seq": 2,
      "atMs": 1020,
      "runPath": "demo@aaaaaaaa/step_a",
      "detail": {
        "type": "stepEntered",
        "stepId": "step_a"
      },
      "evidence": [],
      "evidenceOmitted": 0,
      "truncated": false
    },
    {
      "seq": 3,
      "atMs": 1030,
      "runPath": "demo@aaaaaaaa/step_a#1:act",
      "detail": {
        "type": "actionIntent",
        "callId": "call-1",
        "args": {
          "value": {
            "element": "ssid_field",
            "value": "lab"
          },
          "truncated": false
        }
      },
      "evidence": [],
      "evidenceOmitted": 0,
      "truncated": false
    },
    {
      "seq": 4,
      "atMs": 1040,
      "runPath": "demo@aaaaaaaa/step_a#1:act",
      "detail": {
        "type": "actionSettled",
        "callId": "call-1",
        "outcome": "succeeded"
      },
      "evidence": [],
      "evidenceOmitted": 0,
      "truncated": false
    },
    {
      "seq": 5,
      "atMs": 1050,
      "runPath": "demo@aaaaaaaa/step_a",
      "detail": {
        "type": "observationRecorded",
        "observationId": "obs-1",
        "capturedAtMs": 1030,
        "uiSnapshotOmission": "driverUnsupported"
      },
      "evidence": [
        {
          "id": "asset-e",
          "mediaType": "image/png",
          "sha256": "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
        }
      ],
      "evidenceOmitted": 0,
      "truncated": false
    },
    {
      "seq": 6,
      "atMs": 1060,
      "runPath": "demo@aaaaaaaa/step_a",
      "detail": {
        "type": "assertionEvaluated",
        "assertId": "ssid_was_typed",
        "result": "pass",
        "channel": "dom",
        "reason": "dom text equals the requested ssid"
      },
      "evidence": [],
      "evidenceOmitted": 0,
      "truncated": false
    },
    {
      "seq": 7,
      "atMs": 1070,
      "runPath": "demo@aaaaaaaa/step_a",
      "detail": {
        "type": "verdictRecorded",
        "status": "pass",
        "degraded": false,
        "summary": "all assertions pass on the dom channel"
      },
      "evidence": [],
      "evidenceOmitted": 0,
      "truncated": false
    },
    {
      "seq": 8,
      "atMs": 1080,
      "runPath": "demo@aaaaaaaa/step_a",
      "detail": {
        "type": "stepExited",
        "state": "judged"
      },
      "evidence": [],
      "evidenceOmitted": 0,
      "truncated": false
    },
    {
      "seq": 9,
      "atMs": 1090,
      "runPath": "demo@aaaaaaaa/step_b",
      "detail": {
        "type": "stepEntered",
        "stepId": "step_b"
      },
      "evidence": [],
      "evidenceOmitted": 0,
      "truncated": false
    },
    {
      "seq": 10,
      "atMs": 1100,
      "runPath": "demo@aaaaaaaa/step_b",
      "detail": {
        "type": "humanRequested",
        "requestId": "req-1",
        "purpose": "step",
        "mode": "judge",
        "prompt": "Does the panel show the connected banner?"
      },
      "evidence": [],
      "evidenceOmitted": 0,
      "truncated": false
    },
    {
      "seq": 11,
      "atMs": 1110,
      "runPath": "demo@aaaaaaaa/step_b",
      "detail": {
        "type": "humanResponded",
        "requestId": "req-1",
        "purpose": "step",
        "actor": "cli:tester@host",
        "response": {
          "value": {
            "status": "pass"
          },
          "truncated": false
        }
      },
      "evidence": [],
      "evidenceOmitted": 0,
      "truncated": false
    },
    {
      "seq": 12,
      "atMs": 1120,
      "runPath": "demo@aaaaaaaa/step_b",
      "detail": {
        "type": "verdictRecorded",
        "status": "pass",
        "degraded": false,
        "summary": "human judged pass"
      },
      "evidence": [],
      "evidenceOmitted": 0,
      "truncated": false
    },
    {
      "seq": 13,
      "atMs": 1130,
      "runPath": "demo@aaaaaaaa/step_b",
      "detail": {
        "type": "stepExited",
        "state": "judged"
      },
      "evidence": [],
      "evidenceOmitted": 0,
      "truncated": false
    },
    {
      "seq": 14,
      "atMs": 1140,
      "runPath": "demo@aaaaaaaa",
      "detail": {
        "type": "runFinished",
        "status": "pass",
        "degraded": false
      },
      "evidence": [],
      "evidenceOmitted": 0,
      "truncated": false
    }
  ]
}) satisfies TimelinePage;

import type { StepDossierView } from "../src/step-dossier-view.js";
({
  "projectionVersion": 1,
  "runId": "run-golden",
  "runPath": "demo@aaaaaaaa/step_a",
  "runPathFrames": [
    {
      "kind": "flow",
      "flowId": "demo",
      "irHash": "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    },
    {
      "kind": "step",
      "stepId": "step_a"
    }
  ],
  "stepId": "step_a",
  "effectHash": "sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
  "judgeHash": "sha256:dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
  "resolvedInputs": {
    "element": "ssid_field",
    "value": "lab"
  },
  "preflight": [],
  "attempts": [
    {
      "n": 1,
      "callId": "call-1",
      "outcome": "succeeded",
      "argsSnapshot": {
        "element": "ssid_field",
        "value": "lab"
      },
      "startedAtMs": 1020,
      "finishedAtMs": 1025,
      "intentSeq": 3,
      "settledSeq": 4
    }
  ],
  "output": {
    "value": "lab"
  },
  "observations": [
    {
      "observationId": "obs-1",
      "capturedAtMs": 1030,
      "viewport": {
        "width": 1080,
        "height": 2400,
        "scaleFactor": 2.0
      },
      "screenshot": {
        "asset": {
          "id": "asset-e",
          "mediaType": "image/png",
          "uri": "devicerail://assets/asset-e",
          "sha256": "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
        },
        "sha256": "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
        "localPath": "evidence/sha256/ee/ee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
      },
      "uiSnapshotOmission": "driverUnsupported"
    }
  ],
  "assertionOutcomes": [
    {
      "assertId": "ssid_was_typed",
      "result": "pass",
      "channel": "dom",
      "reason": "dom text equals the requested ssid"
    }
  ],
  "verdict": {
    "status": "pass",
    "degraded": false
  },
  "verdictHistory": [
    {
      "seq": 7,
      "atMs": 1070,
      "verdict": {
        "status": "pass",
        "degraded": false,
        "summary": "all assertions pass on the dom channel",
        "evidence": []
      }
    }
  ],
  "handlerTriggers": [],
  "evidence": [
    {
      "asset": {
        "id": "asset-e",
        "mediaType": "image/png",
        "uri": "devicerail://assets/asset-e",
        "sha256": "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
      },
      "sha256": "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      "localPath": "evidence/sha256/ee/ee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      "source": "observation:obs-1/screenshot"
    }
  ],
  "frame": {
    "inputsSnapshot": {
      "ssid": "lab"
    },
    "vars": {}
  },
  "state": "judged"
}) satisfies StepDossierView;

import type { HumanInboxEntry } from "../src/human-inbox-entry.js";
({
  "projectionVersion": 1,
  "runId": "run-pending",
  "flowId": "demo",
  "requestId": "req-gate",
  "purpose": "supervision",
  "prompt": "about to tap a mutating control",
  "presents": [],
  "requestedAtMs": 2030,
  "requestedSeq": 3,
  "runPath": "demo@aaaaaaaa/guarded",
  "runPathFrames": [
    {
      "kind": "flow",
      "flowId": "demo",
      "irHash": "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    },
    {
      "kind": "step",
      "stepId": "guarded"
    }
  ]
}) satisfies HumanInboxEntry;

import type { RunOverview } from "../src/run-overview.js";
({
  "projectionVersion": 1,
  "runId": "run-golden",
  "flowId": "demo",
  "irHash": "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  "lockfileDigest": "sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
  "deviceId": "fake-device-1",
  "sessionLineage": [
    "session-1"
  ],
  "status": "finished",
  "revision": 14,
  "createdAtMs": 1000,
  "finishedAtMs": 1140,
  "flowVerdictStatus": "pass",
  "flowVerdictDegraded": false,
  "supervisePolicy": null,
  "awaitingHuman": false,
  "steps": {
    "demo@aaaaaaaa/step_a": {
      "state": "judged",
      "verdictStatus": "pass",
      "degraded": false
    },
    "demo@aaaaaaaa/step_b": {
      "state": "judged",
      "verdictStatus": "pass",
      "degraded": false
    }
  }
}) satisfies RunOverview;
