// Generates the type-only surface from the Rust-emitted FlowIR schema
// (schema/generated/flow-ir.schema.json — the truth source is the
// pointlock-ir Rust DTOs, R12), plus a compile-time fixture anchor.
//
// Pipeline: cargo run -p pointlock-ir --bin pointlock-ir-schema-gen
//        → pnpm --filter @pointlock/ir-types generate
//        → pnpm --filter @pointlock/ir-types check

import { compile } from "json-schema-to-typescript";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "../../..");
const schemaPath = join(repo, "schema/generated/flow-ir.schema.json");
const fixtureDir = join(repo, "schema/fixtures/positive");
const srcDir = join(here, "../src");
const testDir = join(here, "../test");

const schema = JSON.parse(await readFile(schemaPath, "utf8"));
const types = await compile(schema, "FlowIR", {
  additionalProperties: false,
  bannerComment:
    "/* Generated from schema/generated/flow-ir.schema.json (pointlock-ir Rust DTOs, R12).\n * Do not edit by hand — run `pnpm generate` after re-emitting the schema. */",
});
await mkdir(srcDir, { recursive: true });
await writeFile(join(srcDir, "flow-ir.d.ts"), types);
await writeFile(
  join(srcDir, "index.d.ts"),
  '/* Generated barrel — see flow-ir.d.ts. */\nexport type { FlowIR } from "./flow-ir";\nexport * from "./flow-ir";\n',
);
console.log("generated src/flow-ir.d.ts");

// Fixture anchor: the minimal golden flow satisfies the generated root
// type. Deliberately ONE fixture: the full corpus trips TypeScript's
// union-inference limits on the FlowIR oneOf forest (TS2590); the
// authoritative fixture judge is the Rust-side behavioral-equivalence
// suite over the SAME corpus (02 §1.1) — this anchor only proves the
// generated surface is real and consumable.
await mkdir(testDir, { recursive: true });
const anchorFixture = "minimal_action.json";
const body = await readFile(join(fixtureDir, anchorFixture), "utf8");
await writeFile(
  join(testDir, "fixtures.generated.ts"),
  [
    "/* Generated by scripts/generate.mjs — DO NOT EDIT BY HAND. */",
    'import type { FlowIR } from "../src/index";',
    "",
    `// ${anchorFixture}`,
    `(${body.trim()}) satisfies FlowIR;`,
    "",
  ].join("\n"),
);
console.log(`generated test/fixtures.generated.ts (anchor: ${anchorFixture})`);
