// Generates the type-only surface from the Rust-emitted projection
// schemas (schema/generated/projection/*.schema.json — the truth source
// is pointlock-store::projection, spine §10.2), plus a compile-time
// fixture anchor: every golden fixture is inlined as a literal and
// `satisfies`-checked against its generated root type, so `pnpm check`
// IS the TS side of the golden-fixture consistency test (02 §1.1).
//
// Pipeline: cargo run -p pointlock-store --bin pointlock-projection-schema-gen
//        → pnpm --filter @pointlock/projection-types generate
//        → pnpm --filter @pointlock/projection-types check

import { compile } from "json-schema-to-typescript";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "../../..");
const schemaDir = join(repo, "schema/generated/projection");
const fixtureDir = join(repo, "schema/fixtures/projection");
const srcDir = join(here, "../src");
const testDir = join(here, "../test");

/** The closed five families (spine §10.1), stem → root type name. */
const FAMILIES = [
  { stem: "flow-graph-view", root: "FlowGraphView", fixture: "flow-graph-view.golden.json" },
  { stem: "run-timeline", root: "TimelinePage", fixture: "run-timeline.golden.json" },
  { stem: "step-dossier-view", root: "StepDossierView", fixture: "step-dossier-view.golden.json" },
  { stem: "human-inbox-entry", root: "HumanInboxEntry", fixture: "human-inbox-entry.golden.json" },
  { stem: "run-overview", root: "RunOverview", fixture: "run-overview.golden.json" },
];

await mkdir(srcDir, { recursive: true });
await mkdir(testDir, { recursive: true });

const banner = `/* Generated by scripts/generate.mjs from schema/generated/projection/ —
 * the Rust DTOs in pointlock-store::projection are the truth source
 * (spine §10.2). DO NOT EDIT BY HAND. */
`;

/** Structural keywords whose absence marks an "any JSON" schema node. */
const STRUCTURAL = [
  "type", "$ref", "enum", "const", "anyOf", "oneOf", "allOf", "not",
  "if", "then", "else", "properties", "items", "prefixItems", "contains",
  "additionalProperties", "patternProperties", "propertyNames", "format",
];

/** Keywords whose value is one schema. */
const ONE_SCHEMA = [
  "items", "additionalProperties", "propertyNames", "not", "if", "then",
  "else", "contains",
];
/** Keywords whose value is an array of schemas. */
const SCHEMA_LIST = ["anyOf", "oneOf", "allOf", "prefixItems"];
/** Keywords whose value is a name→schema map (the map itself is NOT a
 * schema — stamping it would grow a phantom `tsType` property). */
const SCHEMA_MAP = ["properties", "patternProperties", "$defs", "definitions"];

/**
 * json-schema-to-typescript renders an untyped schema (description-only:
 * serde_json::Value fields like presents/resolvedInputs) as a closed
 * object index signature. The honest TS for "any JSON" is `unknown` —
 * forced via the tool's `tsType` extension before compiling. The walk is
 * position-aware: only genuine schema positions are stamped/recursed.
 */
function forceUnknownForUntyped(schema) {
  if (schema === null || typeof schema !== "object" || Array.isArray(schema)) {
    return;
  }
  if (!STRUCTURAL.some((key) => key in schema) && !("tsType" in schema)) {
    schema.tsType = "unknown";
  }
  for (const key of ONE_SCHEMA) {
    if (key in schema) forceUnknownForUntyped(schema[key]);
  }
  for (const key of SCHEMA_LIST) {
    if (Array.isArray(schema[key])) {
      for (const item of schema[key]) forceUnknownForUntyped(item);
    }
  }
  for (const key of SCHEMA_MAP) {
    const map = schema[key];
    if (map && typeof map === "object") {
      for (const value of Object.values(map)) forceUnknownForUntyped(value);
    }
  }
}

const indexExports = [];
const exportedNames = new Set();
for (const family of FAMILIES) {
  const schema = JSON.parse(
    await readFile(join(schemaDir, `${family.stem}.schema.json`), "utf8"),
  );
  forceUnknownForUntyped(schema);
  // No global additionalProperties override: the Rust side already
  // stamps `additionalProperties: false` wherever deny_unknown_fields
  // holds; untyped ledger values (presents, resolvedInputs, …) must
  // stay open (`unknown`), not collapse into closed objects.
  const types = await compile(schema, family.root, {
    bannerComment: banner,
    format: false,
  });
  await writeFile(join(srcDir, `${family.stem}.d.ts`), types);
  // Shared leaf types (StepId, PathFrame, …) are emitted into every family
  // that references them, so a barrel of bare `export *` lines makes those
  // names ambiguous: TypeScript reports TS2308 against this package for any
  // consumer that has not opted into skipLibCheck. Re-export each name from
  // exactly one family — the first that declares it — and let the rest fall
  // through, so the barrel stays unambiguous while every name is reachable.
  const declared = [...types.matchAll(/^export (?:type|interface) (\w+)/gmu)].map(
    (match) => match[1],
  );
  const fresh = declared.filter((name) => !exportedNames.has(name));
  for (const name of fresh) {
    exportedNames.add(name);
  }
  if (fresh.length === declared.length) {
    indexExports.push(`export * from "./${family.stem}.js";`);
  } else if (fresh.length > 0) {
    indexExports.push(
      `export type { ${fresh.join(", ")} } from "./${family.stem}.js";`,
    );
  }
  console.log(`generated src/${family.stem}.d.ts`);
}
await writeFile(join(srcDir, "index.d.ts"), `${banner}${indexExports.join("\n")}\n`);

// The fixture anchor: literals get literal types, so `satisfies` checks
// const fields (projectionVersion: 1) too — unlike resolveJsonModule.
let anchor = `${banner}/* Compile-time golden-fixture anchor: each fixture literal must
 * satisfy its generated root type. */\n`;
for (const family of FAMILIES) {
  const fixture = await readFile(join(fixtureDir, family.fixture), "utf8");
  anchor += `\nimport type { ${family.root} } from "../src/${family.stem}.js";\n`;
  anchor += `(${fixture.trimEnd()}) satisfies ${family.root};\n`;
}
await writeFile(join(testDir, "fixtures.generated.ts"), anchor);
console.log("generated test/fixtures.generated.ts");
